### ISSUE TITLE
ios8 collection view black line on top

### ISSUE THREAD

**Issue by aklokov** [andreamazz/AMScrollingNavbar#100]
For collection view in ios8 it has some issue - clack line on top.
It happens in demo proj too, very easy reproduce - kust load demo proj, press 'collection view' button and scroll...

**Comment by andreamazz** [comment]
Hi @aklokov 
You're right, I forgot to update the collection view's sample. Checkout commit 4d0e621 for a fix, basically you just need to set `useSuperview` to `YES` when using a UICollectionViewController instead of a plain UIViewController.

**Comment by aklokov** [comment]
Yes! it works perfect, thank you!
