### ISSUE TITLE
UIActivityViewController + collapsed navigation bar

### ISSUE THREAD

**Issue by Igor-Palaguta** [andreamazz/AMScrollingNavbar#101]
Open MFMailComposeViewController from UIActivityViewController when navigation bar was collapsed. Dismiss mail controller, navigation bar is expanded, but all items are not visible, probably overlay alpha = 1.0

**Comment by andreamazz** [comment]
Hi @Igor-Palaguta 
Does your controller implement `viewWillDisappear:` by calling `[self showNavBarAnimated:NO];`?

**Comment by Igor-Palaguta** [comment]
Hello @andreamazz 
viewWillDisappear is not called for this case, iOS issue (http://stackoverflow.com/questions/25691723/uiactivityviewcontroller-calls-viewwillappear-but-not-viewwilldisappear)

**Comment by andreamazz** [comment]
Closing this issue. Please refer to this https://github.com/andreamazz/AMScrollingNavbar/issues/146
