### ISSUE TITLE
When NavigationBar is collapsed, content at the top not responding.

### ISSUE THREAD

**Issue by eljago** [andreamazz/AMScrollingNavbar#102]
Hello, great work with the library!

I noticed that when the NavigationBar is collapsed, there is no response when tapping the content that is at the top where the NavigationBar should be.

In the Table View demo if the Nav Bar is collapsed, the search bar doesn't respond.

**Comment by andreamazz** [comment]
Hi @eljago 
We are discussing this issue [here](https://github.com/andreamazz/AMScrollingNavbar/issues/87).
