### ISSUE TITLE
when using custom navigation bar height it remains dim

### ISSUE THREAD

**Issue by yasirmturk** [andreamazz/AMScrollingNavbar#103]
alpha is not being set to 0 when scrolling reaches to top

**Comment by andreamazz** [comment]
Hi @yasirmturk 
Can you reproduce the issue in the sample project?

**Comment by yasirmturk** [comment]
oky i will.. i just made a bar item with a `UIButton`

**Comment by yasirmturk** [comment]
okay the issue is not with custom items but with custom UINavigationBar height, the code is assuming fixed height Navigation Bars and calculating deltas 
`- (float)deltaLimit`

**Comment by andreamazz** [comment]
Hi @yasirmturk 
You are right, I didn't consider a custom height for the navbar. I guess that a fast and easy way to prevent this issue for now is to override `- (float)deltaLimit` providing your own value.

**Comment by yasirmturk** [comment]
dont like overriding a class extension ..are you planning to fix it soon?

**Comment by andreamazz** [comment]
It's hard to make that as general as possible, it would require a set of properties to handle the different states and orientation. In the end it would be a bigger hassle than an override.

**Comment by yasirmturk** [comment]
It was pretty simple actually ..just a bit tricky :)

**Comment by andreamazz** [comment]
Closing this issue. Please refer to this https://github.com/andreamazz/AMScrollingNavbar/issues/146
