### ISSUE TITLE
Jumpy / Disappearing Content on Back Swipe

### ISSUE THREAD

**Issue by nmock** [andreamazz/AMScrollingNavbar#104]
I'm experiencing issues with the content of my ``UITableViewController`` when swiping to go back. I am using a stock ``UITableViewController`` (subclass). Implementation is the same for both ``UITableViewController`` subclasses. iOS 8.1.2. Not using storyboard, all in code.

    - (void)viewDidLoad {
        [super viewDidLoad];
        
        // Scrolling Nav Bar
        [self.navigationController.navigationBar setTranslucent:NO];
        [self followScrollView:self.tableView withDelay:60];
        [self setUseSuperview:YES];
        
        // ...
    }
    
    - (void)viewWillDisappear:(BOOL)animated {
        [super viewWillDisappear:animated];
        [self showNavBarAnimated:NO];
    }

I tried changing ``[self setUseSuperview:YES];`` to ``[self setUseSuperview:NO];`` as mentioned in the ``README``, but it looks like it messes up the content insets at the top.

In addition, sometimes navigation elements (title and right bar button) will disappear and then reappear when swiping to go back but letting it cancel, not sure if it is a related issue, but including it here. 

Here is a video of the first issue in action: https://www.dropbox.com/s/jvgbhrzdaonuan2/IMG_1345.MOV?dl=0

**Comment by andreamazz** [comment]
Hi @nmock 
Sorry for the massive delay. This should be related to #125
