### ISSUE TITLE
Unrecognized selector sent to instance?

### ISSUE THREAD

**Issue by pangelovski** [andreamazz/AMScrollingNavbar#105]
Hi 
I get this strange error and it started after I installed Cocoapods and installed the latest AMScrollingNavbar version.
[HomeTableViewController followScrollView:]: unrecognized selector sent to instance 0x7fbf935962b0

I have followed the guide in the readme.
I have posted my code here... https://gist.github.com/pangelovski/c4577808fb0242f63106
Note, the HomeTableViewController is of type UITableViewController and not UIViewController.
Is this causing the problem?

**Comment by andreamazz** [comment]
Hi @pangelovski 
This should work fine, the only thing that's probably missing is the import of the category at the top:
```objc
#import "UIViewController+ScrollingNavbar.h"
```

**Comment by pangelovski** [comment]
I should have mentioned that I already did that, but I managed to fix the issue. It turned out that when executing 'pod install' I got some error messages....

[!] The `<APPNAME> [Debug]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-<APPNAME>/Pods-<APPNAME>.debug.xcconfig'. This can lead to problems with the CocoaPods installation


I needed to go to my Target --> Build Settings -->Other linker flags and add $(inherited)

**Comment by andreamazz** [comment]
:+1:
