### ISSUE TITLE
Scrolling shows black bar instead of moving up

### ISSUE THREAD

**Issue by shahankit** [andreamazz/AMScrollingNavbar#106]
Tried the exact steps as in the video but it's not working properly.
Tried on xcode 6.1.1 and ios 8 on iphone 6 simulator.
link to output : https://drive.google.com/file/d/0B0mJU7nj9pwrdXV3cXFmWmZXa00/view?usp=sharing

**Comment by andreamazz** [comment]
Are you using a UITableViewController? If that's the case use:
`[self setUseSuperview:NO]`

**Comment by shahankit** [comment]
No, I am not using UITableViewController. Its a simple ViewController. I had followed all the steps in the video exactly as show. Though I gave it a try by adding the statement that you suggested, but the result is still the same.

**Comment by andreamazz** [comment]
If you are using a UIViewController you need to pass YES to that method instead.

**Comment by shahankit** [comment]
Thanks @andreamazz it worked :+1:
