### ISSUE TITLE
Enabling scrolling Navbar with extension view using TableView

### ISSUE THREAD

**Issue by shahankit** [andreamazz/AMScrollingNavbar#107]
I'm using TableView similar to ScrollView in you demo project but doing so only the navigation bar scrolls away, the extra view that I added similar to yours in ScrollView demo does nor scroll away. Can you send me some video regarding that or any changes required.

**Comment by andreamazz** [comment]
Hi @shahankit 
Did you add an autolayout constraint and passwd to the category with:
```objc
    [self setScrollableViewConstraint:self.yourHeaderConstraint withOffset:<#someOffset#>];
```
?

**Comment by shahankit** [comment]
hello @andreamazz I've not used any constraints either in storyboard or code.

**Comment by andreamazz** [comment]
That's the only way to attach a custom header.

**Comment by shahankit** [comment]
Thanks added headerConstaints and it solved the problem.
