### ISSUE TITLE
followScrollView unrecognized selector sent to instance

### ISSUE THREAD

**Issue by shahankit** [andreamazz/AMScrollingNavbar#109]
I installed the pod in my existing application and have a view of height 40 followed by a table view in my view controller. I did exactly as in the video. I have methods implemented for my tableview. I added the following code to my ViewController's ViewDidLoad:
```objc
[self followScrollView:self.tblView withDelay:60];
[self setUseSuperview:YES];
[self setScrollableViewConstraint:self.headerConstraint withOffset:40];
[self setShouldScrollWhenContentFits:NO];
```

But it gives uncaught exception and on checking exceptions I got the following error:
```
[myClass followScrollView:withDelay:]: unrecognized selector sent to instance 0x7f8b7bd56d60
```

**Comment by andreamazz** [comment]
Take a look at this issue: https://github.com/andreamazz/AMScrollingNavbar/issues/105
It has to be a configuration problem, since the runtime system can't find the method exported by the class extension.

**Comment by shahankit** [comment]
Thank you for replying back and solving the issue. The build setting solved the issue. But now on scrolling the Navigation bar goes up showing black screen and then extension view goes up. While coming down it comes perfectly. Do you have any ideas what may be causing the issue. I've given headerconstraint to Top Layout Guide for the Extenision View.

**Comment by andreamazz** [comment]
Are you using a UITableViewController? If that's the case use:
`[self setUseSuperview:NO]`

**Comment by shahankit** [comment]
No I'm using simple ViewController as I did previously containing a View followed by TableView.
![screen shot 2015-01-22 at 4 11 47 pm](https://cloud.githubusercontent.com/assets/4739743/5854276/0fb07748-a252-11e4-8db1-6321567de76c.png)

**Comment by andreamazz** [comment]
Is setUseSuperview set to YES then?

**Comment by shahankit** [comment]
@andreamazz I've kept setUseSuperView to YES, but removing it or even setting it no keeps the output same. Also, Here is the video of the issue that I am facing - https://www.youtube.com/watch?v=8w32I3hqlnE Hope it may help to debug the issue well.

**Comment by andreamazz** [comment]
Hi @shahankit 
Sorry for the delay. Can you provide some code to reproduce the issue, or even better, reproduce the issue in the demo project?

**Comment by shahankit** [comment]
Thank you @andreamazz for replying. I won't be able to reproduce the problem now, but will try to reproduce the problem in a demo project and will post the link of code here, most probably after a week.

**Comment by shahankit** [comment]
Hello @andreamazz Sorry for delay. This is demo project with the same issue: https://github.com/shahankit/ScrollingNavBarIssue.

**Comment by andreamazz** [comment]
This fixes the issue:
```
    self.navigationController.navigationBar.translucent = NO;
    [self followScrollView:self.tableView];
    [self setUseSuperview:YES];
```

**Comment by shahankit** [comment]
Thanks that solved the problem. Great help thank you again.

**Comment by andreamazz** [comment]
Happy to help :+1: 
Cheers
