### ISSUE TITLE
Handling of gesture cancel state

### ISSUE THREAD

**Issue by Igor-Palaguta** [andreamazz/AMScrollingNavbar#110]
in handlePan method also add check for UIGestureRecognizerStateCancelled. In other case navigation bar can remain gray all the time. E.g. when application was closed during scrolling

    if ([gesture state] == UIGestureRecognizerStateEnded || [gesture state] == UIGestureRecognizerStateCancelled) {

**Comment by andreamazz** [comment]
Nice catch, thanks. Fixed in b012ab9
