### ISSUE TITLE
Using AMScrollingNavbar with UITableViewController, some times appears black header on top.

### ISSUE THREAD

**Issue by KanybekMomukeyev** [andreamazz/AMScrollingNavbar#111]
Using AMScrollingNavbar with UITableViewController, some times appears black header on top.
There also UISearchBar.
Used this one, no changes, have the latest version:
[self setUseSuperview:NO];

Top viewController is UINavigationController, root view controller is UITableViewController which uses scroll navbar, when user press some button, root view controller is moved to UIViewController.
If user wants to return to UITableViewController, which will be as root view controller, this issue happens.

![ios simulator screen shot jan 31 2015 9 30 53](https://cloud.githubusercontent.com/assets/866641/5986675/20b425e4-a92d-11e4-92d1-a807de262d2d.png)

**Comment by andreamazz** [comment]
Do you show the navbar when the controller disappars?
```objc
- (void)viewWillDisappear:(BOOL)animated
{
    [super viewWillDisappear:animated];
    [self showNavBarAnimated:NO];
}
```

**Comment by KanybekMomukeyev** [comment]
@andreamazz, yes i did.

**Comment by andreamazz** [comment]
You are referring to the nav controller's rootViewController... are you using the push segue or are you manually changing the root?

**Comment by KanybekMomukeyev** [comment]
when using like this one:
[self.navigationController setViewControllers:@[self.someViewController] animated:NO];

and like this one
[self.navigationController popViewController];
here root controller is TableViewController(scrollabe), also appears this issue

**Comment by andreamazz** [comment]
I'm not sure if `setViewControllers:` fires the viewWillDisappear call in the child that's being removed. try calling the showNavbar: method before changing root:
```objc
[self.oldViewController showNavBarAnimated:NO];
[self.navigationController setViewControllers:@[self.someViewController] animated:NO];
```

**Comment by KanybekMomukeyev** [comment]
- (CGFloat)tableView:(UITableView *)tableView heightForHeaderInSection:(NSInteger)section
     {
        return  40;
    }

    - (UIView *)tableView:(UITableView *)tableView viewForHeaderInSection:(NSInteger)section
    {
        self.headerView.headerTitleLabel.text = [SIActualDataManager sharedInstance].tableHeaderTitle;
        return self.headerView;
    }

I removed header view for tableView, and everything working best!

**Comment by andreamazz** [comment]
Glad to hear that! :+1:
