### ISSUE TITLE
when using viewControllers inside scrollview Black window appears when scroll up and viewcontroller view's top part hide inside navbar 

### ISSUE THREAD

**Issue by sunny45** [andreamazz/AMScrollingNavbar#113]
when using viewControllers inside scrollview Black window appears when scroll up and viewcontroller view's top part hide inside navbar 

black window appears when i use translucent properties to no .and if i keep translucent property to YES THEN black window does not appear but uiview top part hide inside nav bar. 

issue is that i am using scrollview and calling 4 four view inside it .

**Comment by andreamazz** [comment]
I really can't understand a word, no offense. Can you provide some sample code presenting the issue?

**Comment by sunny45** [comment]
![screen shot 2015-02-02 at 10 16 58 am](https://cloud.githubusercontent.com/assets/10141150/5995959/d1b4bd48-aac4-11e4-8747-d96add599d87.png)


here you can see when i scroll up you can see black window or black navigation bar appear

**Comment by sunny45** [comment]
this is the code in viewdidload .where i am using a scrollview and  i am calling 4 views inside scrollview

[self.navigationController.navigationBar setTranslucent:YES];
   HomeViewController *home = [self.storyboard instantiateViewControllerWithIdentifier:@"HomeViewController"];
    home.view.frame = self.view.bounds;

    [self addChildViewController:home];
    [self.scrollView addSubview:home.view];
    [home didMoveToParentViewController:self];
    
    RecentViewController *recent = [self.storyboard instantiateViewControllerWithIdentifier:@"RecentViewController"];
    
    CGRect frame = recent.view.frame;
    frame.origin.x = self.scrollView.frame.size.width*1;
  
    recent.view.frame = frame;
    
    [self addChildViewController:recent];
    [self.scrollView addSubview:recent.view];
    [recent didMoveToParentViewController:self];

    
    
    FriendsViewController *friends=[self.storyboard instantiateViewControllerWithIdentifier:@"FriendsViewController"];
    CGRect frame1 = friends.view.frame;
    frame1.origin.x = self.scrollView.frame.size.width*2 ;

    friends.view.frame = frame1;
    
    [self addChildViewController:friends];
    [self.scrollView addSubview:friends.view];
    [friends didMoveToParentViewController:self];
    
    
    RandomViewController *random=[self.storyboard instantiateViewControllerWithIdentifier:@"RandomViewController"];
    CGRect frame2 = random.view.frame;
    frame2.origin.x = self.scrollView.frame.size.width * 3;
    random.view.frame = frame2;
    
    [self addChildViewController:random];
    [self.scrollView addSubview:random.view];
    [random didMoveToParentViewController:self];
    
    [self scrollView].contentSize = CGSizeMake(self.scrollView.frame.size.width * 4, self.scrollView.frame.size.height);
    [self.scrollView setPagingEnabled:YES];
    [self.scrollView setShowsHorizontalScrollIndicator:NO];

----------------------------------------------------------------------------------------------------
And in view Controller's ViewDidLoad 

 [self followScrollView:self.homeCollectionView];



every thing works perfect but only black window appears when using Translucent properties to NO
and if i don't use Translucent property then it my top view move inside the navigation bar

Please help me out

**Comment by andreamazz** [comment]
Hi @sunny45 
The translucent navbar is not supported, so you should keep the property set to `NO`. 
The black bar might be due to a config issue, try using this call:
```objc
[self setUseSuperview:NO];
```
Use NO if you are using a UIScrollViewController or YES if you are using a plain UIViewController.

**Comment by sunny45** [comment]
while keeping translucent navbar property  to NO.
i See black Bar And if i remove or comment it it works fine

and where do i use this code

[self setUseSuperview:NO];

bcoz i have one container view i.e Scrollview viewcontrller

which contains 4 views  for sliding

**Comment by andreamazz** [comment]
Call it in the same VC you are calling followScrollView:

**Comment by sunny45** [comment]
[self setUseSuperview:NO];

when i use this code i get this error

no visible @interface for 'Mycontroller' declares the selector 'setsuperview:'

 thanks for the reply

**Comment by andreamazz** [comment]
Make sure you are using the latest verison of the lib, and that you are calling that method in the same view controller (followScrollview: is declared in the same file as setSuperView:, so it has to work).

**Comment by sunny45** [comment]
[self setUseSuperview:Yes];

i tried that one but still getting the same issue .

no visible @interface for 'Mycontroller' declares the selector 'setsuperview:'


One thing forgot to mention that my 4  viewcontrollers have collection view
in it .I am using collection inside the view controllers .So that i can
swipe between them

**Comment by andreamazz** [comment]
To reiterate: `setSuperview:` is declared in the same file as `followScrollView:` as you can see here:
https://github.com/andreamazz/AMScrollingNavbar/blob/master/AMScrollingNavbar/UIViewController%2BScrollingNavbar.h

Therefore if the compiler can't find the declaration you are either using an older version, or callign the method in the wrong file or in the wrong casing.
