### ISSUE TITLE
frame of scrollableView should not change (or shouldn't feel so) while trying to hide navigation bar (enhancement) 

### ISSUE THREAD

**Issue by radhakrishnapai** [andreamazz/AMScrollingNavbar#115]
Hi

I would like to post a suggestion for an enhancement. The frame of the scrollableView changes when trying to hide or show the navbar. As a result, the view seems to be jumpy and is not much user friendly when used in apps with complex design and detailed subviews. 

The vine app uses a similar approach but their scrollableView frame does not seem to change. Correct me if I am wrong. :) 
I have tried many ways to modify this library to achieve a similar effect but all in vain. Could you please look into this? It would be very much appreciated. Please find the attached vine video to show the expected result. 
Many Thanks in advance!

https://www.dropbox.com/s/cwv9f05x9ao9x2w/Vine_sample_video.MOV?dl=0

**Comment by andreamazz** [comment]
Hi @radhakrishnapai 
I don't think they are using a navigation controller at all to be honest :smile:  but I might be wrong. By the looks of it it's just a UIView or a plain UINavigationBar (notice how the navbar items slide under the statusbar).  
You are right on the _jumpyness_ though, I've been meaning to do a major refactoring of the library for a while now.

**Comment by radhakrishnapai** [comment]
I did notice the navigation bar items sliding under the status bar. What I think they did is add a subview to the window, with the frame of the status bar. The colour of this view can then be changed accordingly. I have implemented this in my app. :)

**Comment by andreamazz** [comment]
Closing this issue. Please refer to this https://github.com/andreamazz/AMScrollingNavbar/issues/146
