### ISSUE TITLE
NavBar not completely hidden

### ISSUE THREAD

**Issue by chlebta** [andreamazz/AMScrollingNavbar#116]
Hello, It's really great work's and very simple to use, but I got wired issue while scrolling up the navBar is not completely hidden check the picture please.
![capture d ecran 2015-02-23 a 11 57 46](https://cloud.githubusercontent.com/assets/1204608/6326577/57fe9b46-bb53-11e4-9fc8-ec44921153d6.png)
![capture d ecran 2015-02-23 a 11 57 19](https://cloud.githubusercontent.com/assets/1204608/6326578/59af776c-bb53-11e4-82ba-0000d871be3c.png)

**Comment by andreamazz** [comment]
Hi @chlebta 
That's weird, can you reproduce the issue on the sample project by any chance?

**Comment by chlebta** [comment]
Hi, I've solved this it was conflict with UItoolbar. thank's and sorry

**Comment by andreamazz** [comment]
No problem, I'm glad it's working fine :+1:
