### ISSUE TITLE
Request : Change sequence of scrolling of navigation bar and extension view while hiding 

### ISSUE THREAD

**Issue by shahankit** [andreamazz/AMScrollingNavbar#117]
Hello @andreamazz Just a small request in case you have time. I want to change the hiding sequence of navigation bar and extension view i.e. the extension view should first move in followed by navigation bar. I saw this type of feature in tlyShyNavBar (https://github.com/telly/TLYShyNavBar) library. Link to gif :https://raw.githubusercontent.com/telly/TLYShyNavBar/master/resources/ShyNavBar-1.gif. The sequence in which the extension view and navigation bar appear is perfect.

**Comment by andreamazz** [comment]
It was requested the way I implemented it now, but I can add an option to reverse the order. I'll add it to the TODO list :smile:

**Comment by shahankit** [comment]
Just in case you don't want to change the order. Can you tell me which
piece of to alter regarding same. I try to change the order by myself if
possible.

**Comment by andreamazz** [comment]
Closing this issue. Please refer to this https://github.com/andreamazz/AMScrollingNavbar/issues/146
