### ISSUE TITLE
Scrolling weird using UIWebView

### ISSUE THREAD

**Issue by adbeel92** [andreamazz/AMScrollingNavbar#118]
See video: https://dl.dropboxusercontent.com/u/51052713/navscroll-issue-2.mp4

My code has:
[self.navigationController.navigationBar setTranslucent:NO];
[self followScrollView:self.webView];

StoryBoard:
HideBottomBarOnPush is TRUE, because we need hide the tab bar of the TabBarController
![captura de pantalla 2015-03-06 23 42 23](https://cloud.githubusercontent.com/assets/991840/6540116/96985d32-c45a-11e4-8a46-ae256f2be4a3.png)

Any idea why happens that. Thanks

**Comment by andreamazz** [comment]
Hi @adbeel92 
Try different settings of this method call:
```objc
[self setUseSuperview:NO];
```
Use NO if you are using a plain UIViewController, YES if you are using a tableviewcontroller.

**Comment by adbeel92** [comment]
I've just set that and it still has the same weird behavior.

Have you tried using UIWebView?

**Comment by andreamazz** [comment]
Sure, the demo app in this repo uses a UIWebView

**Comment by runia** [comment]
I have the same issue. UITableView represent establish normal. A problem UIWebView.

**Comment by andreamazz** [comment]
Can you reproduce this in the demo app?

**Comment by NicholasTD07** [comment]
Are you using AutoLayout for the view? Doesn't look like it has any constraints.

I am using a UIWebView with AMScrollingNavbar too. I do use AutoLayout to constraint the UIWebView.
No problem at all. 😄

This is my project repo, https://github.com/NicholasTD07/SwiftDaily-ZhiHu. You can search `NavBar` in my commits, and see where I made changes related to AMScrollingNavbar. There are only four commits where I did something related to AMScrollingNavbar.

**Comment by andreamazz** [comment]
Closing this issue. Please refer to this https://github.com/andreamazz/AMScrollingNavbar/issues/146
