### ISSUE TITLE
Unresponsive UIButton when Nav Bar is scrolled

### ISSUE THREAD

**Issue by yogoo** [andreamazz/AMScrollingNavbar#120]
In some instance a ```UIButton``` does not respond to taps when the ```Navigation Bar``` is scrolled.
I wrote an [example to illustrate it](https://github.com/yogoo/AMScrollingNavbar/tree/feature/unresponsiveUIButton).

**Comment by andreamazz** [comment]
Hi @yogoo 
Uhm, where's the button in that sample? The changelog is massive, so I might be looking in the wrong place.

**Comment by yogoo** [comment]
Hi @andreamazz, I should have been more specific.

Clone the repo and launch the demo. There's only this example in it. The button will logs a message when tapped. Scroll the bar and tap the button, the button's state doesn't change and no message is logged.

**Comment by andreamazz** [comment]
Your fork contains the same demo app as the master. Are you sure you pushed the right code?

**Comment by yogoo** [comment]
yup, in the branch unresponsiveUIButton ^_^

**Comment by andreamazz** [comment]
Uops, my bad.

**Comment by andreamazz** [comment]
Ok, I see what you mean. This is the same as this:
https://github.com/andreamazz/AMScrollingNavbar/issues/87
Using constraints doesn't update correctly the frame, so the area below is unresponsive. Currently I have no clue on how to solve this.

**Comment by yogoo** [comment]
I'll do some more testing and will post back here if I find anything relevant.

**Comment by andreamazz** [comment]
Thanks, I appreciate it :+1:

**Comment by H3rrVorrag3nd** [comment]
Could you solve the issue? Having the same problem with links in a UIWebView - the links on top of the page are not clickable (the ones on bottom of the page are clickable). Only if I scroll top again, the links are working again.

**Comment by andreamazz** [comment]
Not really, PRs are welcome. 
In the meantime if you switch to the _frame_ version this issue should disappear. Use the method without the input layout constraint:
```objc
[self followScrollView:self.scrollView];
```

**Comment by andreamazz** [comment]
This is related to this:
https://github.com/andreamazz/AMScrollingNavbar/issues/87

Also, I started the rewrite of the library in swift, as a subclass of `UINavigationController`. You can find the starting code in the `swift` branch, if you want to check it out. This supports translucent navbars now, and the setup is easier, but I still have a lot of tinkering to do. Feedback is welcome.
