### ISSUE TITLE
NavBar in NavigationController

### ISSUE THREAD

**Issue by danrudolf1** [andreamazz/AMScrollingNavbar#121]
When I use this NavBar in a navigation controller I'm having some issues. If I push a new controller onto the stack when the bar is collapsed it is also collapsed in the destination controller. Is there a way to set this so its alway present in the destination controller?

**Comment by andreamazz** [comment]
Hi @danrudolf1 
Make sure to call this in your `viewWillDisappear:`:
```objc
- (void)viewWillDisappear:(BOOL)animated
{
    [super viewWillDisappear:animated];
    [self showNavBarAnimated:NO];
}
```

**Comment by danrudolf1** [comment]
Thanks, thats exactly what i was looking for.

**Comment by andreamazz** [comment]
:+1:
