### ISSUE TITLE
Compile issue when used as framework with Swift (1.2) and latest CocoaPods

### ISSUE THREAD

**Issue by thomey** [andreamazz/AMScrollingNavbar#122]
There seems to be a namespacing(?) issue when used as a framework with Swift and latest CocoaPods.

If you have multiple view controllers implementing the `gestureRecognizer(gestureRecognizer: UIGestureRecognizer, shouldReceiveTouch touch: UITouch)`, the compiler will complain:  `Overriding declaration requires an 'override' keyword` as soon as you import AMScrollingNavbar to one of the view controllers.

Shouldn't AMScrollingNavbar only affect the gesture recognizer of the view controller it was imported to?

Steps to reproduce:
Just make a new Swift project using latest CocoaPods.

Podfile:
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

pod 'AMScrollingNavbar'
```

ViewController.swift:
```
import UIKit
import AMScrollingNavbar

class ViewController: UIViewController {
  override func viewWillDisappear(animated: Bool) {
    super.viewWillDisappear(animated)
    
    showNavBarAnimated(false)
  }
}

extension ViewController: UIGestureRecognizerDelegate {
  func gestureRecognizer(gestureRecognizer: UIGestureRecognizer, shouldReceiveTouch touch: UITouch) -> Bool {
    return true
  }
}
```

SecondViewController.swift
```
import UIKit

class SecondViewController: UIViewController {
}

extension SecondViewController: UIGestureRecognizerDelegate {
  func gestureRecognizer(gestureRecognizer: UIGestureRecognizer, shouldReceiveTouch touch: UITouch) -> Bool {
    return true
  }
}
```

Sometimes you can "trick" it to build by commenting out the import and then back again, but most of the time it will fail. Could it be related to the new incremental builds introduced in Swift 1.2?

**Comment by andreamazz** [comment]
Hi @thomey 
The problem is that once you import the module, this module is available in all classes of the project, so a UIViewController class extension is applied to all of your UIViewControllers. There's nothing I can do about it AFAIK, sorry.
