### ISSUE TITLE
Visible nav bar with zero alpha views after dismissing modal. 

### ISSUE THREAD

**Issue by markst** [andreamazz/AMScrollingNavbar#123]
If my nav bar is offset because of scrolling & then I present & modal view, my nav bar is fully visible with no visible buttons:

![ios simulator screen shot 14 apr 2015 2 48 21 pm](https://cloud.githubusercontent.com/assets/274318/7130535/63b74c24-e2b5-11e4-9fef-b8c46d611367.png)

**Comment by markst** [comment]
a resolution for this is setting the modal presentation style to: `UIModalPresentationOverFullScreen`

**Comment by andreamazz** [comment]
Should also be related (and fixed) to #125
