### ISSUE TITLE
navigationBar items dissapear on when using search

### ISSUE THREAD

**Issue by lenkaiser** [andreamazz/AMScrollingNavbar#125]
When the the user navigates back and forth trough the tableview but remains in the tableview demo the items in the navigationBar disappear when the search bar is tapped. As you can see before:
![screen shot 2015-04-30 at 16 26 42](https://cloud.githubusercontent.com/assets/1133235/7414899/e43a03e4-ef55-11e4-8e0e-dddc8b77469f.png)

and after:
![screen shot 2015-04-30 at 16 27 06](https://cloud.githubusercontent.com/assets/1133235/7414898/e41ad21c-ef55-11e4-8f41-7a02801948e7.png)

To recreate this situation do the following:
1. Open tableview demo
2. Click on first item
3. Navigate back
4. Press search bar and cancel it 
5. See the magic happen.

**Comment by henryeverett** [comment]
I'm also experiencing this bug.

**Comment by henryeverett** [comment]
I have figured out a workaround for this bug.

Assuming you're having the same issue I am, where pushing and popping a new VC on the navigation controller and using the search bar can cause the navigation items to disappear, it's because the overlay view is added as a subview on top of itself and loses its original pointer.

I fixed it by moving the followScrollView method call from viewDidAppear to viewDidLoad.
Another option would be to add stopFollowingScrollView to viewDidDisappear.

Ideally, the library should prevent itself from adding multiple overlays to the same nav bar.

**Comment by andreamazz** [comment]
> Ideally, the library should prevent itself from adding multiple overlays to the same nav bar.

Indeed. I'll fix it as soon as possible. Thanks for the feedback :+1:

**Comment by andreamazz** [comment]
Ok, I gave it some thought. There's one major thing missing in the sample's implementation, and I never thought about it... once the controller is deallocated, `stopFollowingScrollView` should be called. This way the previous overlay gets cleaned. 

```objc
- (void)dealloc {
    [self stopFollowingScrollView];
}
```

This fixes the issue. I'll make sure to update the doc.

:+1:

**Comment by andreamazz** [comment]
Checkout commit 5a961cf with the updated sample.

**Comment by lenkaiser** [comment]
@andreamazz Only the problem actually occurs in my application even when I'm haven't clicked on a row/view controller just solely when I click the search bar . So where should the stopFollowingScrollView method have to be called then?

**Comment by andreamazz** [comment]
Check these lines https://github.com/andreamazz/AMScrollingNavbar/blob/master/ScrollingNavbarDemo/ScrollingNavbarDemo/AMTableViewController.m#L70-L74

**Comment by lenkaiser** [comment]
@andreamazz My view controller is exactly as the example, I already implemented the searchBarTextDidEndEditing method but it doesn't seem to work. Do you have any suggestions that might be the cause of this problem?

**Comment by andreamazz** [comment]
HI @lenkaiser it's hard to tell, can you reproduce by any chance the issue on the sample app provided with this repo?
