### ISSUE TITLE
@import when modules are disabled

### ISSUE THREAD

**Issue by iceNuts** [andreamazz/AMScrollingNavbar#126]
Hi there,

I met a weird bug, when I change the file to be mm file. The compiler pops up an error: ```@import when modules are disabled```. What's more, I have set up Xcode with modules ```enabled``` in LLVM 6.1.

Is there anyone know the reason?

Thanks.

**Comment by andreamazz** [comment]
Seems a common issue with Xcode when you import a library that uses the @import directive from a Objective-C++ file:
https://github.com/IFTTT/FastttCamera/issues/13

I can revert to the old `#import` if needed, let me know.

**Comment by iceNuts** [comment]
Cool, please revert it back. I do it manually and it works fine.

**Comment by andreamazz** [comment]
Done, you'll find the old import in pod version `1.3.6`

**Comment by iceNuts** [comment]
Thanks.
