### ISSUE TITLE
Black opaque blocks when scrolling up

### ISSUE THREAD

**Issue by alex4814** [andreamazz/AMScrollingNavbar#129]
I think the problem is close to what is posted in Issue#80.

However, I want to clarify that a little bit. I was just doing the [video demo][1], and found this:

![sample](https://cloud.githubusercontent.com/assets/963917/7671100/b7c586b4-fcf0-11e4-86ad-2110fc4274ad.gif)

The difference is that I rewrite demo in swift, and set the **navigationBarAppearace** in AppDelegate.
I've taken a close look at things that needs to be careful, and I followed every step from within the video.

What is the problem?

[1]: https://vimeo.com/92721470

**Comment by andreamazz** [comment]
Hi @alex4814 
Try setting this property:
```swift
self.setUseSuperview(false)
```

**Comment by alex4814** [comment]
@andreamazz i was using a plain UIViewController, so I didn't put this statement according to *Using it with UITableViewController or UICollectionViewController*. 
Anyway, I did as you said(I put it in the **viewDidLoad**, may be a wrong place?). Unfortunately, it still remains the same as before.

**Comment by andreamazz** [comment]
Hi, did you also try with 
```
self.setUseSuperview(true)
```
I also get the two cases mixed up :sweat_smile:

**Comment by alex4814** [comment]
= =, Well, that works. BTW, is it able to hide/show toolbars along with navigation controller as well when scroll down/up ?

**Comment by andreamazz** [comment]
No, toolbars are not currently supported.
