### ISSUE TITLE
Prompt support 

### ISSUE THREAD

**Issue by benoit-pereira-da-silva** [andreamazz/AMScrollingNavbar#134]
Adding a prompt to the nav bar breaks the current implementation.
```objectiveC
self.navigationItem.prompt=@"Prompt text"
````

**Comment by andreamazz** [comment]
Yeah, the prompt really break things. I can probably fix this by changing the height constants used in the checks. I'll get back to you soon.

**Comment by andreamazz** [comment]
Ok, I've added the support for prompts, although there's a bug when a controller with the prompt is popped from the stack. Checkout commit 6d8b6e0

**Comment by andreamazz** [comment]
Closing this issue. Please refer to this https://github.com/andreamazz/AMScrollingNavbar/issues/146
