### ISSUE TITLE
Navigation bar title doesn't disappear

### ISSUE THREAD

**Issue by modastic** [andreamazz/AMScrollingNavbar#136]
![bug](https://cloud.githubusercontent.com/assets/3118117/8097298/9fd5421c-0fae-11e5-950c-300de18906e7.gif)

The title on the nav bar doesn't seem to be disappearing. The nav bar buttons seem to be working fine. I do have a custom view attached to the nav bar but that doesn't seem to be the problem. 

Here's my code:
```
    self.navigationItem.title = @"Title";
    
    [self.navigationController.navigationBar setTranslucent:NO];
    [self.navigationController.navigationBar setBarTintColor:[UIColor colorWithWhite:1.f alpha:.1f]];
    
    [self.navigationController.navigationBar setShadowImage:[UIImage imageNamed:@"TransparentPixel"]];
    [self.navigationController.navigationBar setBackgroundImage:[UIImage imageNamed:@"Pixel"] forBarMetrics:UIBarMetricsDefault];
    
    UIButton *searchButton = [[UIButton alloc] initWithFrame:CGRectMake(0, 0, 40, 40)];
    [searchButton setBackgroundImage:[UIImage imageNamed:@"search"] forState:UIControlStateNormal];
    
    self.navigationItem.leftBarButtonItem = [[UIBarButtonItem alloc] initWithCustomView:searchButton];
```

**Comment by andreamazz** [comment]
Hi @modastic 
Can you check the view hierarchy with the hierarchy inspector in xcode? When the navbar is collapsed there should be a UIView above it, like this:
![screen shot 2015-06-11 at 16 15 54](https://cloud.githubusercontent.com/assets/570797/8109085/3b629a3a-1055-11e5-8efc-e129a4ebe842.png)

Can you do a quick check?

**Comment by modastic** [comment]
Hi @andreamazz,

This is what the view hierarchy looks like when the nav bar is collapsed. Seems like there is a view in front of it, but its not covering the title?

![bug2](https://cloud.githubusercontent.com/assets/3118117/8109408/7d72b94a-1024-11e5-90be-ed2a59df4941.png)

**Comment by andreamazz** [comment]
Mmmm, I'm not sure, that view looks transparent from the screenshot, which is weird. Can you by any chance upload some code presenting the issue (or can you reproduce the issue in the sample app)? It would help a lot the debug process.

**Comment by JinkProject** [comment]
Same issue with me. Using the non-autolayout option.

  [self followScrollView:self.collectionView];
    [self.navigationController.navigationBar setTranslucent:NO];

**Comment by NicholasTD07** [comment]
@modastic Is the navigationBar set to non-transparent? When I did it first time, I missed that and had what you have in my table view. I watched and followed the steps in that setup video. And then everything works.

**Comment by andreamazz** [comment]
Closing this issue. Please refer to this https://github.com/andreamazz/AMScrollingNavbar/issues/146
