### ISSUE TITLE
NavBar hidden when back

### ISSUE THREAD

**Issue by prsolucoes** [andreamazz/AMScrollingNavbar#138]
Hi,

I'm using it on my apps and after some updates, i checked that when i press home button and back to app after, the navbar change to hidden.

I got the source code from github, execute the sample and the same problem happen with official sample.

Is this a problem or feature?

**Comment by andreamazz** [comment]
Yeah, looks like it was a feature added to fix issue #97 
But now that I look at it, it makes no sense. I'll work around it.

**Comment by andreamazz** [comment]
Should be fine now
