### ISSUE TITLE
When swipe back from edge of the screen, the scroll should disable

### ISSUE THREAD

**Issue by iCell** [andreamazz/AMScrollingNavbar#143]
- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer {
        if ([gestureRecognizer isKindOfClass:[UIScreenEdgePanGestureRecognizer class]]) {
            return NO;
        }
        return YES;
    }

**Comment by andreamazz** [comment]
Good point, thanks!

**Comment by NicholasTD07** [comment]
@andreamazz Is it possible to disable vertical scrolling when user is swiping on a UITableViewCell?

**Comment by iCell** [comment]
[self.tableView setScrollEnabled:NO];

**Comment by NicholasTD07** [comment]
@iCell Could you explain it in detail? For example, where should I call this?

**Comment by iCell** [comment]
@NicholasTD07 I think I‘ve already explained clearly in my comment.

**Comment by NicholasTD07** [comment]
@iCell I am not saying that I want to disable vertical scrolling at any time, but only when the user is swiping a table view cell to see the action items, like the "Archive" option in "Mail" app which is shown when user swipe horizontally on a `UITableViewCell`.

**Comment by iCell** [comment]
I said **after swiping a cell** you can use the code to disable the scrolling.

**Comment by NicholasTD07** [comment]
@iCell I want to disable the vertical scrolling when the user **is** swiping, which starts from when user starts to swipe and ends at when the user stops....

**Comment by iCell** [comment]
@NicholasTD07 All right, you can detect the state of swipeGesture(or panGesture) in that cell, when the user starts to swipe, the state of the gesture should be UIGestureRecognizerStateBegan, and UIGestureRecognizerStateEnded when the swiping is ended. You can add a panGesture to the cell or maybe there's some ways to get the swiping gesture on the cell.

**Comment by NicholasTD07** [comment]
@iCell I would like to see whether there is a solution that uses UITableViewCell itself without any modification. :)

**Comment by iCell** [comment]
@NicholasTD07 I suggest you to subclass a UITableViewCell to implement what you want.
