### ISSUE TITLE
Navigation bar header image hidden on search controller

### ISSUE THREAD

**Issue by prsolucoes** [andreamazz/AMScrollingNavbar#144]
Problem: 
Navigation bar header image hidden on search controller

Steps:
1. Open example project
2. Click on button "table view"
3. Click on first item of table view 
4. Click on searchbar to type a text
5. Click on cancel button
6. BUM! The header is hidden again :(

**Comment by andreamazz** [comment]
Yeah... I'm in the process of rewriting the whole thing in swift and as a subclass of UINavigationController. This should clean the code quite a lot. There's only one problem... I wrote the core a couple of years ago and right now
![amdogd606lsdzkghjorv](https://cloud.githubusercontent.com/assets/570797/8876780/25040a6e-3222-11e5-9f65-2b483ded2ee8.jpg)

There are a lot of hacks that I hope to get rid of, as soon as i remember why they were put in place.

**Comment by andreamazz** [comment]
Hi @prsolucoes 
I started the rewrite of the library in swift, as a subclass of `UINavigationController`. You can find the starting code in the `swift` branch, if you want to check it out. This supports translucent navbars now, and the setup is easier, but I still have a lot of tinkering to do. Feedback is welcome.

**Comment by andreamazz** [comment]
Closing this issue. Please refer to this https://github.com/andreamazz/AMScrollingNavbar/issues/146
