### ISSUE TITLE
[beta] Release 2.0.0-beta5

### ISSUE THREAD

**Issue by andreamazz** [andreamazz/AMScrollingNavbar#146]
The library was rewritten in Swift, as a subclass of `UINavigationController`. 
This version contains major breaking changes.  
Moving from a category to a subclass cleaned up the code quite a bit, making it more maintainable and hopefully less fragile. It also fully supports translucent navbars now.  

I'm closing all current Issues, please test this new version if you can, your feedback is important and always welcome. If this version does not fix your issue encountered in `1.5` and previous, please feel free to reopen the issue. 

This is a work in progress, I ported most of the features, but some of them are missing: 
- [X] test with UITableViewControllers
- [X] improved documentation
- [X] improved demo project
- [X] delegate methods
- [ ] test coverage (as of #131)
- [ ] floating header

I'm going to keep track of the new changes and bugs here.

The version `1.x` won't be maintained in the future, for now I'll create a new branch, `v1.x`, for hotfixes.  

Thank you all for your contribution and feedback.

**Comment by shahankit** [comment]
Thanks @andreamazz for porting the library to Swift

**Comment by NicholasTD07** [comment]
Would it be a better idea to provide functionality in `ScrollingNavigationViewController` as methods in an extension of `UIView` which can be more flexible compared to subclassing?

**Comment by andreamazz** [comment]
Hi @NicholasTD07 
Version 1.x was provided as an extension of `UIViewController`, and in the end it was a mess. Too many breaking points, and too many associated objects, that rendered the code quite ugly. The library needs to have full control over the navigation bar and the container view of the navigation controller, so to me it makes perfect sense to subclass `UINavigationController`. I'm not myself a fan of subclassing, but in this case I think it's the best solution.

**Comment by NicholasTD07** [comment]
@andreamazz Yes, I agree with you that `ScrollingNavigationController` should be done by subclassing `UINavigationController`. What I was trying to say is the functionality in `ScrollingNavigationViewController`.

Extract following snippets into an extension of `UIView`
```
        if let navigationController = self.navigationController as? ScrollingNavigationController {
            navigationController.showNavbar(animated: true)
        }
```

```swift
        if let navigationController = self.navigationController as? ScrollingNavigationController {
            navigationController.stopFollowingScrollView()
        }
```

```swift
    /**
        On appear calls `showNavbar()` by default
    */
    override public func viewWillDisappear(animated: Bool) {
        super.viewWillDisappear(animated)

        if let navigationController = self.navigationController as? ScrollingNavigationController {
            navigationController.showNavbar(animated: true)
        }
    }

    /**
        On disappear calls `stopFollowingScrollView()` to stop observing the current scroll view, and perform the tear down
    */
    override public func viewDidDisappear(animated: Bool) {
        super.viewDidDisappear(animated)

        if let navigationController = self.navigationController as? ScrollingNavigationController {
            navigationController.stopFollowingScrollView()
        }
    }

    /**
        Calls `showNavbar()` when a `scrollToTop` is requested
    */
    public func scrollViewShouldScrollToTop(scrollView: UIScrollView) -> Bool {
        if let navigationController = self.navigationController as? ScrollingNavigationController {
            navigationController.showNavbar(animated: true)
        }
        return true
    }
```

**Comment by andreamazz** [comment]
The important part of that class are the overrides :)  
In any case that class is meant as an optional utility class, to avoid some boilerplate code, if you don't want or can't subclass your view controller, you can implement those overrides in your own code.

**Comment by ryanfitz** [comment]
@andreamazz Im trying out the latest version on master (Beta 4 version) and am running into scrolling issues when using AMScrollingNavbar with a tab bar controller. 

I put together an [example](https://github.com/ryanfitz/AMScrollingNavbar/tree/tabbar-example/examples/TabBar) which demonstrates the bug. Load up the app in either simulator or real device and about 50% of the time scrolling on the tableviews does not work properly. Try scrolling on a tableview then switch tabs, scroll again and then move back to the previous tab and attempt to scroll. Scrolling doesn't break 100% of the time, but after a few attempts it will stop properly working.

**Comment by andreamazz** [comment]
Huh, if you enable the scroll indicator, the first time you scroll you always break scrolling.

**Comment by andreamazz** [comment]
Looks like its the opaque bar. If you set the navbar to translucent the issue goes away. I'll try and figure out why.

**Comment by andreamazz** [comment]
Ok, it's this call:
https://github.com/andreamazz/AMScrollingNavbar/blob/master/Source/ScrollingNavigationController.swift#L219

Commenting that out fixes the issue. I need to find a smarter way to keep the content steady while the navbar is scrolling.

**Comment by andreamazz** [comment]
@ryanfitz 
I think I got it. Took the chance to simplify the code a bit also. Checkout the latest version:
```
pod 'AMScrollingNavbar', :head
```

**Comment by ryanfitz** [comment]
@andreamazz Your fix is working great for me so far, thanks. I'm loving the switch to swift, you've managed to make this lib so straightforward and simple to understand.

**Comment by andreamazz** [comment]
:+1: 
I'll push a new beta later today, hopefully restoring the delegate methods. Cheers

**Comment by andreamazz** [comment]
Ok, released `2.0.0` with Swift 2.0 syntax. 
Will push the floating header to the next release.

**Comment by evgenydash** [comment]
@andreamazz I'm getting the same #135 with this version on iPad.

**Comment by andreamazz** [comment]
Hi @evgenydash 
Can you reproduce this in the demo project? I'm trying but with no luck.

**Comment by andreamazz** [comment]
Nevermind, I was able to reproduce it.

**Comment by evgenydash** [comment]
@andreamazz The issue was than nav bar frame is not updated. I'm tried with this funny code in the orientation change notification:

        CGRect navBarFrame = self.navigationController.navigationBar.frame;
        navBarFrame.size.width -= 1;
        self.navigationController.navigationBar.frame = navBarFrame;
        navBarFrame.size.width += 1;
        self.navigationController.navigationBar.frame = navBarFrame;

**Comment by andreamazz** [comment]
That's odd. It's still broken in the demo project, even with that hack. 
It only happens on iPad and in landscape. Using Reveal I can see that the navbar position is ok, but it's only rendering part of it: 
<img width="1056" alt="screen shot 2015-10-23 at 15 51 02" src="https://cloud.githubusercontent.com/assets/570797/10694343/e43372a4-799d-11e5-8ad5-a61a3e206ea3.png">
