### ISSUE TITLE
Umbrella header Warning

### ISSUE THREAD

**Issue by yunuserenguzel** [andreamazz/AMScrollingNavbar#150]
Hi I am using beta6 and I get this error
...<module-includes>:1:1: Umbrella header for module 'AMScrollingNavbar' does not include header 'AMScrollingNavbar.h'

is there any way to silence this warning?

**Comment by andreamazz** [comment]
Hi @yunuserenguzel 
How are you installing the lib? Cocoapods, Carthage or manually?

**Comment by yunuserenguzel** [comment]
Hi @andreamazz 
Thanks for the quick reply!

I am using cocoapods. Here my Podfile:

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

pod 'Alamofire', '~> 1.3'
pod 'RESideMenu', '~> 4.0.7'
pod 'DateTools'
pod 'JWTDecode', '~> 0.3'
pod 'AMScrollingNavbar', '2.0.0-beta6'

use_frameworks!

**Comment by yunuserenguzel** [comment]
I am including the framework using `import AMScrollingNavbar` otherwise I cannot use its classes. Is there any way to properly include the framework?

**Comment by andreamazz** [comment]
`import AMScrollingNavbar` is the correct way to import the framework over your project.  
As for the warning, I tried a fresh install on a new project and I got no warnings. What version of cocoapods are you using? (`pod --version`)

**Comment by yunuserenguzel** [comment]
my version is `0.36.1`

Hearing fresh install from you, I clean and build the project and the warning is gone now. 
Thanks for your help and sorry for the inconvenience

**Comment by andreamazz** [comment]
Great :+1: 
Make sure to update cocoapods though, this issue is related to an old issue resolved in the latest releases.

**Comment by yunuserenguzel** [comment]
Thanks :+1: 
i will do it
