### ISSUE TITLE
Accessing subviews of UINavigationBar to change alpha

### ISSUE THREAD

**Issue by yunuserenguzel** [andreamazz/AMScrollingNavbar#151]
Hello,

I start to use AMScrollingNavbar 2.0.0-beta6, however it doesn't change the alpha of left UIBarButtonItem and navigationItem.title while collapsing

As a solution I have added these lines 
```Swift
for view:UIView in navigationBar.subviews as! [UIView]{
  if view.classForCoder.description() == "UINavigationButton" ||
    view.classForCoder.description() == "UINavigationItemView" {
      view.alpha = alpha
  }
}
```
in `updateNavbarAlpha()` and it worked. Do you think it is good to access subviews of uinavigationbar like this?

**Comment by andreamazz** [comment]
It should be ok, but I rather directly reference them. Can you reproduce the issue in the sample project, so I can take a look at it?

**Comment by yunuserenguzel** [comment]
Here I have reproduce the bug in a sample project

https://github.com/yunuserenguzel/AMScrollingNavbarSampleProject

**Comment by andreamazz** [comment]
Ace :+1: 
Ok, I took a look at it, and looks like the easier way is accessing the views as you did, otherwise the code becomes a mess. I'll push a new version.

**Comment by andreamazz** [comment]
Fixed in https://github.com/andreamazz/AMScrollingNavbar/blob/master/CHANGELOG.md#200-beta7

**Comment by yunuserenguzel** [comment]
Oh great! 
Thanks :)

**Comment by james-ff** [comment]
Hello,

Would it be possible to patch this fix into the last objective-c version?

Thanks

**Comment by andreamazz** [comment]
Hi. Sure, I'll get around it tomorrow if I can.

**Comment by andreamazz** [comment]
Ok, checkout branch `v1.x`

**Comment by james-ff** [comment]
Cheers!

**Comment by james-ff** [comment]
@andreamazz How do i get the v1.x branch from Cocoapods? I have set it but the pod isn't moving up in version when I call update. It is on 1.5.1 currently

**Comment by andreamazz** [comment]
```
pod 'AMScrollingNavbar', git: 'https://github.com/andreamazz/AMScrollingNavbar', branch: 'v1.x'
```

**Comment by james-ff** [comment]
Installed and it is working.

Thanks mate!
