### ISSUE TITLE
UISegmentedControl in UINavigationBar not hiding

### ISSUE THREAD

**Issue by pangelovski** [andreamazz/AMScrollingNavbar#153]
When adding a UISegmentedControl to the navigation bar, the segmented control is not hiding when scrolling.

**Comment by andreamazz** [comment]
Nice catch, I'll fix it ASAP.

**Comment by andreamazz** [comment]
Hi @pangelovski 
I'm testing this in the sample project and seems to be working fine: http://d.pr/v/t0eu

Which version are you using?

**Comment by pangelovski** [comment]
Hi @andreamazz, Im running an objective c project with the Swift version 2.0.0. 
I should note that I added this line in the SwiftNavigationController.swift file

            /**
            if view.classForCoder.description() == "UINavigationButton" || view.classForCoder.description() == "UINavigationItemView" {
                view.alpha = alpha
            }
            **/
            
            if view.classForCoder.description() == "UINavigationButton" || view.classForCoder.description() == "UINavigationItemView" || view.classForCoder.description() == "UISegmentedControl" {
                view.alpha = alpha
            }

**Comment by andreamazz** [comment]
Seems reasonable. I've integrated the fix in version `2.0.1`.
