### ISSUE TITLE
We still need the documentation for 1.x

### ISSUE THREAD

**Issue by CavalcanteLeo** [andreamazz/AMScrollingNavbar#154]
Please, create a wiki page for 1.x documentation.

**Comment by andreamazz** [comment]
Hi @CavalcanteLeo 
You can checkout the documentation of the `v1.x` branch:
https://github.com/andreamazz/AMScrollingNavbar/tree/v1.x

**Comment by CavalcanteLeo** [comment]
Thank you

**Comment by andreamazz** [comment]
:+1:
