### ISSUE TITLE
AMScrollingNavbar does not take into account the UITabBar

### ISSUE THREAD

**Issue by pangelovski** [andreamazz/AMScrollingNavbar#156]
I have noticed that if you have a UITabBar, AMScrolling Navbar is not taking this into account and is cutting the last 49px (height of the UITabBar). I have fixed this in my own code by checking if the views navigation controller is a ScrollingNavigationController and setting the content insets manually.

**Comment by andreamazz** [comment]
Hi @pangelovski 
Commit d783476 should fix the issue. Let me know if this works for you.

**Comment by andreamazz** [comment]
Closing this, let me know if the issue persists.
