### ISSUE TITLE
Cannot use 2.x versions with Objective-C project

### ISSUE THREAD

**Issue by fatalaa** [andreamazz/AMScrollingNavbar#157]
I didn't find a guide about how to use AMScrollingNavbar 2.x from Objective-C.
Is there any way to do it?

**Comment by andreamazz** [comment]
Sure, it should work fine, what issue did you find?

**Comment by andreamazz** [comment]
Here's a quick demo in Objective-C
http://d.pr/f/1cK1X

**Comment by fatalaa** [comment]
I found the official way to use it, just accidentally forgot to close the issue, but thanks.

**Comment by andreamazz** [comment]
:+1:
