### ISSUE TITLE
It would be nice to be able to disable the scrolling navbar temprorarily

### ISSUE THREAD

**Issue by erikackermann** [andreamazz/AMScrollingNavbar#165]
I have run into scenarios while using this component where I want to hide the navbar and let the user scroll the `scrollableView` around without affecting the navbar.  If I hide the navbar and then call `-stopFollowingScrollView`, the navbar is immediately re-shown, so this doesn't work.

What I am currently doing is subclassing the ScrollNavigationController and overriding the UIGestureRecognizerDelegate method like this:

```swift
    func gestureRecognizer(gestureRecognizer: UIGestureRecognizer, shouldReceiveTouch touch: UITouch) -> Bool {
        return self.scrollingNavbarEnabled
    }
```

I have added that `scrollingNavbarEnabled` property to my subclass.  Would this toggle make sense to add to ScrollingNavigationController?  Because there is probably a better place to disable the scrolling nav bar.

**Comment by andreamazz** [comment]
Hi @erikackermann 
That sounds like a good idea. I'll add a property to pause the scrolling in the next release.

**Comment by andreamazz** [comment]
Hi @erikackermann 
Commit ceffb9d adds the `scrollingEnabled` property. It defaults to `true`, and can be set to `false` to pause the scrolling. 

Cheers

**Comment by erikackermann** [comment]
Fantastic!  Thanks for this.
