### ISSUE TITLE
Can't prevent Nav Bar from showing when app becomes active

### ISSUE THREAD

**Issue by erikackermann** [andreamazz/AMScrollingNavbar#168]
There is this property: `expandOnActive`, which I can set to `false`, but when the app is foregrounded, a UIDeviceOrientationDidChangeNotification event is also triggered and that causes the nav bar to appear.  Is there some way I can prevent this event from being called?

Or could we add a property like `expandOnRotation` that does a similar thing to `expandOnActive`?

**Comment by andreamazz** [comment]
It can be done (adding the expandOnRotation), but it might cause issues. I had to handle the rotation notification because the rotation was causing graphical glitches.

**Comment by erikackermann** [comment]
Do you know if it is normal that UIDeviceOrientationDidChangeNotification is called when the app comes to foreground?

**Comment by andreamazz** [comment]
Yeah. I see your point, if you opt out of the `expandOnActive` the navigation bar is expanded anyway. 
I can probably kill the notification and use `viewWillTransitionToSize:withTransitionCoordinator:` instead. I'll do some tests and get back to you

**Comment by erikackermann** [comment]
Thank you.  Let me know how I can help.

On Wed, Nov 11, 2015 at 5:59 AM, Andrea Mazzini <notifications@github.com>
wrote:

> Yeah. I see your point, if you opt out of the expandOnActive the
> navigation bar is expanded anyway.
> I can probably kill the notification and use
> viewWillTransitionToSize:withTransitionCoordinator: instead. I'll do some
> tests and get back to you
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andreamazz/AMScrollingNavbar/issues/168#issuecomment-155736265>
> .
>



-- 

Erik Ackermann

Mobile Development

(212) 951-0496

LinkedIn <http://www.linkedin.com/in/erikackermann>

176 Grand Street, 3rd Floor - New York, NY 10013

**Comment by andreamazz** [comment]
Ok, I did some digging. I tried removing the rotation handler all together, and when the app comes to the foreground the navigation bar position is reset. This is probably done by UIKit. 
This means that `expandOnActive` is pretty much useless, and needs to default to `true`.  
I'm probably going to remove it in the next release. Any ideas?

**Comment by erikackermann** [comment]
Is there a way we can keep track of the orientation from before the app
went to the background, and only show the navbar if this orientation
actually changed?

On Fri, Nov 13, 2015 at 4:40 AM, Andrea Mazzini <notifications@github.com>
wrote:

> Ok, I did some digging. I tried removing the rotation handler all
> together, and when the app comes to the foreground the navigation bar
> position is reset. This is probably done by UIKit.
> This means that expandOnActive is pretty much useless, and needs to
> default to true.
>
> I'm probably going to remove it in the next release. Any ideas?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andreamazz/AMScrollingNavbar/issues/168#issuecomment-156378558>
> .
>



-- 

Erik Ackermann

Mobile Development

(212) 951-0496

LinkedIn <http://www.linkedin.com/in/erikackermann>

176 Grand Street, 3rd Floor - New York, NY 10013

**Comment by andreamazz** [comment]
We could, but it won't change the fact that UIKit resets the navigation bar :)  
I disabled the `expandOnActive` and the rotation handler, and the navbar is still shown by UIKit (with invisible elements, since `showNavbar:` is not called). So...

**Comment by erikackermann** [comment]
Ah, I see.  What if we re-hide the navbar (if it was previously hidden)
manually when the app is foregrounded?

On Mon, Nov 16, 2015 at 10:32 AM, Andrea Mazzini <notifications@github.com>
wrote:

> We could, but it won't change the fact that UIKit resets the navigation
> bar :)
>
> I disabled the expandOnActive and the rotation handler, and the navbar is
> still shown by UIKit (with invisible elements, since showNavbar: is not
> called). So...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andreamazz/AMScrollingNavbar/issues/168#issuecomment-157068983>
> .
>



-- 

Erik Ackermann

Mobile Development

(212) 951-0496

LinkedIn <http://www.linkedin.com/in/erikackermann>

176 Grand Street, 3rd Floor - New York, NY 10013

**Comment by andreamazz** [comment]
I tried, no dice. It should be done with a delay, which is rather ugly.

**Comment by erikackermann** [comment]
Maybe this is quite difficult to do.  I just noticed that in Instagram's
app, if you hide the nav bar and then background/foreground the app, the
nav bar reappears.  So, maybe apps that use this library just need to be
aware that the nav bar will be reappearing when the app is foregrounded.

On Mon, Nov 16, 2015 at 11:38 AM, Andrea Mazzini <notifications@github.com>
wrote:

> I tried, no dice. It should be done with a delay, which is rather ugly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andreamazz/AMScrollingNavbar/issues/168#issuecomment-157091231>
> .
>



-- 

Erik Ackermann

Mobile Development

(212) 951-0496

LinkedIn <http://www.linkedin.com/in/erikackermann>

176 Grand Street, 3rd Floor - New York, NY 10013

**Comment by andreamazz** [comment]
You're absolutely right. I'm going to remove the option and make it clear. 
Although, I'm pretty sure that this was working on iOS7..

**Comment by erikackermann** [comment]
Lame :(

Well, thanks for your attention on this issue.

On Mon, Nov 16, 2015 at 11:51 AM, Andrea Mazzini <notifications@github.com>
wrote:

> You're absolutely right. I'm going to remove the option and make it clear.
> Although, I'm pretty sure that this was working on iOS7..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andreamazz/AMScrollingNavbar/issues/168#issuecomment-157094950>
> .
>



-- 

Erik Ackermann

Mobile Development

(212) 951-0496

LinkedIn <http://www.linkedin.com/in/erikackermann>

176 Grand Street, 3rd Floor - New York, NY 10013

**Comment by andreamazz** [comment]
No problem. I'm closing this for now, but I'm still interested in solving this, I'll let you know if I find some workaround.
