### ISSUE TITLE
"Scroll to Top" & Jumping bug on small scrolls

### ISSUE THREAD

**Issue by whitefoxy** [andreamazz/AMScrollingNavbar#170]
Hello,

It is wonderful library, but I seed some bugs or maybe I am using it wrong.
1. In TableView when I am (for example) in the middle of the table, I am pressing the status bar and system scrolls me to the top, but the navigation bar doesn't want to expand. What is wrong?
2. When I am making small scrolls (From Up to Down) maybe 1-5 px and I am seeing that the scroll bar jumps like a crazy.
3. (Just question) Is it possible to add the same effect like in Instagram app? They are not just hiding the navigation bar, but "Minimize" it. I just don't know how to describe this effect correctly, but it look much more better.

**Comment by andreamazz** [comment]
Hi @whitefoxy 

> In TableView when I am (for example) in the middle of the table, I am pressing the status bar and system scrolls me to the top, but the navigation bar doesn't want to expand. What is wrong?

You need to implement this:
```swift
    /**
     Calls `showNavbar()` when a `scrollToTop` is requested
     */
    public func scrollViewShouldScrollToTop(scrollView: UIScrollView) -> Bool {
        if let navigationController = self.navigationController as? ScrollingNavigationController {
            navigationController.showNavbar(animated: true)
        }
        return true
    }
```
I'll explicit this step in the readme.




> When I am making small scrolls (From Up to Down) maybe 1-5 px and I am seeing that the scroll bar jumps like a crazy.

Are you able to reproduce this in the demo project? I tried and seems to be working fine.  




> (Just question) Is it possible to add the same effect like in Instagram app? They are not just hiding the navigation bar, but "Minimize" it. I just don't know how to describe this effect correctly, but it look much more better.

Yeah, I know what you mean, it's pretty cool and it's on my TODO list :)

**Comment by whitefoxy** [comment]
Thank you for quick response.

1. This code work fine, but I think it should be `override func` not `public func`.
2. I think it is not really big problem, as I looked other apps they have the same issue.

When Navigation bar is shown try to repeat making scrolls down (1-10px) fast (one by one) and you will see that navigation bar want to hide, but because it is very small scroll system don't let it to hide. And it looks a little bit strange (Navigation bar starts hiding, but because of small scroll it shows back, it looks like navigation bar jumps). Maybe I am the only one who sometimes scrolls in such manner :D

3. This is very good news. I'll be looking forward to this feature!
