### ISSUE TITLE
Crash saying "dyld: Library not loaded"

### ISSUE THREAD

**Issue by ffittschen** [andreamazz/AMScrollingNavbar#171]
Hi,
I tried to install your framework using Carthage, but it always crashes upon App start with this error message:

```
dyld: Library not loaded: @rpath/AMScrollingNavbar.framework/AMScrollingNavbar
  Referenced from: /var/mobile/Containers/Bundle/Application/6EFFBEB7-2C9D-457E-9377-52399B2AF445/TemplateApp.app/TemplateApp
  Reason: image not found
```

It is a swift App with 8.0 Deployment Target using Xcode 7.1.1

Do you know how this can be fixed?

**Comment by andreamazz** [comment]
Are you including the framework in the Embedded binaries?

**Comment by ffittschen** [comment]
I just realized, that I built a different target than the one I added the library to... Sorry 🙈

**Comment by andreamazz** [comment]
:) No problem. 

cheers
