### ISSUE TITLE
UICollectionView with pinned headers issue

### ISSUE THREAD

**Issue by Aigai0s** [andreamazz/AMScrollingNavbar#172]
I am using an UICollectionView with pinned headers (`flowLayout.sectionHeadersPinToVisibleBounds = true`). The problem is that the headers do not float up to the navigation bar as seen below.

<img width="313" alt="screenshot" src="https://cloud.githubusercontent.com/assets/7319168/11767690/1033680c-a1b5-11e5-9a31-600b79ead33d.png">
@andreamazz already noticed that the issue disappears when you are using a non translucent navigation bar.

[PinnedSectionHeaders.zip](https://github.com/andreamazz/AMScrollingNavbar/files/60481/PinnedSectionHeaders.zip)

**Comment by andreamazz** [comment]
Hi @Aigai0s 
Checkout the latest commit, the issue should be fixed. If you are using CocoaPods you can pull the latest version like this:
```
pod 'AMScrollingNavbar', :head
```
