### ISSUE TITLE
Black Bar on scroll (when pushing a view with a search controller in navigation bar)

### ISSUE THREAD

**Issue by Errortype520** [andreamazz/AMScrollingNavbar#174]
The navbar scrolls perfectly on first load. When I navigate away using a ViewController from another storyboard, and then return with a back button, I get the issue with a black bar:

<img width="368" alt="screen shot 2015-12-21 at 11 04 24 am" src="https://cloud.githubusercontent.com/assets/5439331/11934964/1c32197c-a7d3-11e5-84b9-7f627a99c947.png">

The black bar corrects itself when scrolling up.

**EDIT**: [See better description below of issue below](https://github.com/andreamazz/AMScrollingNavbar/issues/174#issuecomment-166491337)

**Comment by andreamazz** [comment]
Hi @Errortype520 
Did you implement this in the `viewWillDisappear`?
https://github.com/andreamazz/AMScrollingNavbar/blob/master/Source/ScrollingNavigationViewController.swift#L13-L19

**Comment by andreamazz** [comment]
I made it more clear in the readme:
https://github.com/andreamazz/AMScrollingNavbar#handling-navigation

**Comment by Errortype520** [comment]
No, I had only implemented the viewDidDisappear. But even after implementing viewWillAppear, the issue remains.

**Comment by andreamazz** [comment]
Sorry, I meant `viewDidDisappear`, no need to implement `viewWillAppear` if you already did.

**Comment by andreamazz** [comment]
So, when you push the new controller you don't see the navbar moving down (use the slow animation debug option in the simulator). 
Can you make sure that `showNavbar` is called?

**Comment by Errortype520** [comment]
Whoops, that was a typo by me, here is the code:

```swift
override func viewWillAppear(animated: Bool) {
    super.viewWillAppear(animated)
    if let navigationController = self.navigationController as? ScrollingNavigationController, tableView = self.tableView {
        navigationController.followScrollView(tableView, delay: 50)
    }
}

override func viewWillDisappear(animated: Bool) {
    super.viewWillDisappear(animated)
    if let navigationController = self.navigationController as? ScrollingNavigationController {
        navigationController.showNavbar(animated: true)
    }
}

override func viewDidDisappear(animated: Bool) {
    super.viewDidDisappear(animated)
    if let navigationController = self.navigationController as? ScrollingNavigationController {
        navigationController.stopFollowingScrollView()
    }
}
```
Pushing the view controller from another StoryBoard:

```swift
@IBAction func handleNavigationSearchItem(sender:AnyObject?) {
    // Get the search controller
    guard let application = UIApplication.sharedApplication().delegate as? AppDelegate,
            navcontroller = application.viewControllerFromStoryboard("Search") as? UINavigationController,
               controller = navcontroller.viewControllers.first
    else { return }
    
    self.navigationController?.pushViewController(controller, animated: true)
}
```

**Comment by Errortype520** [comment]
The navigation shows correctly. When I push a new view controller (specifically from another storyboard as a segue works fine) and return to the original view. When I start scrolling the navigation moves upand disappears, but the content remains in place. When the scrolling hits a threshold (I believe when it is fully collapsed) the content jumps back up under the status bar.

**Comment by andreamazz** [comment]
Got it, I'll try to reproduce this.

**Comment by Errortype520** [comment]
![simulator screen shot dec 21 2015 9 26 09 pm](https://cloud.githubusercontent.com/assets/5439331/11946520/81a1f632-a829-11e5-97c7-3625d0fa99ef.png)

I created a new project to test if I could recreate it, but it all seems to be working. I will keep looking at it and see if I can find the issue

**Comment by Errortype520** [comment]
Ok. Man, what a pain to track down but I found the issue. I added a Search bar to the "Settings View" in the navigation header:

![simulator screen shot dec 21 2015 10 08 14 pm](https://cloud.githubusercontent.com/assets/5439331/11947048/8e8abdba-a82f-11e5-8654-d9b6dffa961a.png)

This causes the issue with the black bar when returning to the previous view:

![simulator screen shot dec 21 2015 10 05 09 pm](https://cloud.githubusercontent.com/assets/5439331/11947053/9d539c68-a82f-11e5-8708-04270d6c285a.png)

I will find a work around for this strange issue.

**Comment by worthbak** [comment]
@Errortype520 @andreamazz any resolution or workaround for this one? I'm seeing it when pushing a view that has a custom titleView (not a searchController, just a plain UIView subclass).

**Comment by andreamazz** [comment]
Sorry I had no time to look at this. I hope to get a chance to catch up on issues around the next week. 
In the meantime any help is appreciated

**Comment by avitorio** [comment]
@Errortype520 @andreamazz @worthbak Hi guys, did any of you find a solution to this? I've been on it for hours, just now realised the problem is because of the Navigation Item... Not sure where to go from here.

**Comment by andreamazz** [comment]
Hi @avitorio 
Thanks for the heads up, I've updated the readme with the standard paypal page.

Back to the issue, this happens when adding a navigation item where? Left and right items should work, looks like the issue is in the title view. Can you reproduce the issue in the sample project?

**Comment by avitorio** [comment]
@andreamazz hey man, thanks for the help. I ended up going with another solution. The line below did the trick.

`self.navigationController.hidesBarsOnSwipe = YES;`

**Comment by andreamazz** [comment]
Yes, that is the official iOS API :)

**Comment by lxian** [comment]
I encountered the same problem. And I made a workaround by:

1. Hide the navigation controller's navigation bar when the view appears
2. Create a new navigation bar. Add buttons, title view etc to it.
3. Show the navigation controller's navigation bar when the view disappears
