### ISSUE TITLE
Start tracking after scrollView reach Y offset

### ISSUE THREAD

**Issue by chlebta** [andreamazz/AMScrollingNavbar#175]
Hello, thank you for this amazing library.
I need to know if is it possible to make the following scrollView behaviour work only after reaching a defined Y offset.
Example : 

```
if offsetY > 200 {
navbar start follow scrollview direction
} else {
keep showing the navbar
}
```

**Comment by andreamazz** [comment]
Hi. Yes, that's what the `delay` parameter is for:
```swift
navigationController.followScrollView(tableView, delay: 200.0)
```

**Comment by chlebta** [comment]
`delay` will set after scrolling how much the navbar follow scrollview not in which Y follow the scrollView.
What I need to do is : tell AMScrollingNavBar don't change any thing don't hide the navbar if scrollview.contentOffset.y < 500

**Comment by andreamazz** [comment]
That's what the `delay` does. The first 500 points of content offset are ignored, once they are over, the navbar starts scrolling. You can see this behaviour in the sample project (the first element).

**Comment by chlebta** [comment]
I've tried in demoProject to set delay to 200 but scrolling up will hide the navbar before reaching 200

**Comment by andreamazz** [comment]
Mmmm.... yeah, that's broken.  
Great.  
I'll fix it as soon as I can.

**Comment by andreamazz** [comment]
Checkout latest commit and please let me know.

**Comment by chlebta** [comment]
Sorry for taking time to reply.
So the problem is not totally fixed for example if I set the delay to 200 then : 
 * it will follow the scrollview only If ofsetY> 200
 * But also first 200 points after offsetY == 200 will be ignored that means the navBar will hide at 400
