### ISSUE TITLE
Broken Demo build

### ISSUE THREAD

**Issue by SpiraMira** [andreamazz/AMScrollingNavbar#177]
HI
1 - the 7.1 development branch of Quick/Nimble no longer exists
2 - when I replace by pod "Nimble"  then pod install, I get errors building the Nimble libraries, FBSnap.. and the test case. Seems like the workspace isn't set up correctly since Xcode can't find Nimble headers.

Using Xcode 7.2 and your latest master

Don't  yet know much about Quick and Nimble - just wondering if it is something obvious before I delve into it further.

I disabled tests in the demo project for now and the actual demo builds and runs fine.

Thanks in advance.

**Comment by andreamazz** [comment]
Thanks for the heads up, I'll fix it as soon as possible.

**Comment by SpiraMira** [comment]
No problem.  I know testing is under development. 
Great framework by the way. Great guidance and inspiration to roll my own open source.

**Comment by andreamazz** [comment]
It should be fine now. I also removed the Pods folder from the ignore to avoid future headaches.
