### ISSUE TITLE
CollectionView Scrolling Problem

### ISSUE THREAD

**Issue by burakyldz** [andreamazz/AMScrollingNavbar#178]
Hi,

I'm trying to implement collectionView your codes into my project(UIViewController -> CollectionView) . But when i scrool up or down, screen scrool doesnt work properly. Sometimes scrolling work properly but sometimes doesnt work. 

How can i fix this problem ?

Or

If you have a sample project using collenctionView, could you send me please ? 

Thanks.

**Comment by andreamazz** [comment]
I'll add a sample in the demo app soon.

**Comment by burakyldz** [comment]
Thank you so much, I'm waiting for your demo app.

I was working on this problem 2 two days, but I have no solution yet.

**Comment by andreamazz** [comment]
Closing this, let's continue in #184
