### ISSUE TITLE
use_frameworks! - incompatibility with my other pods

### ISSUE THREAD

**Issue by Shamsiddin** [andreamazz/AMScrollingNavbar#179]
When I wanted to include latest version of ```AMScrollingNavbar``` to my ```Objective C``` project. But I got some errors happened with my other ```Objective C``` pods. As ```use_frameworks!``` flag is the required with ```Swift``` pods, it's properly used on your library. But what if I wanted to use your library and at the same time not include ```use_frameworks!``` for my other pods. Cocoapods documentation says I can't use ```use_frameworks!``` flag only for specific pods. For this reason I wanted to know is there any way to include ```AMScrollingNavbar``` manually into my project, if so which files should be included, or please provide the instruction for manually including.

**Comment by andreamazz** [comment]
Hi @Shamsiddin 
`use_frameworks!` should work for Objective-C pods too without issues. What kind of errors are you encountering?  
In any case, you can either use [Carthage](https://github.com/Carthage/Carthage), or manually integrate the dynamic framework that you find bundled in the [releases](https://github.com/andreamazz/AMScrollingNavbar/releases).  
You can also set a bridging header and integrate the sources, but the aforementioned options are easier.

**Comment by Shamsiddin** [comment]
Oh sure, thanks for your mention about manually integration the dynamic framework. 
My problem was that when I included use_frameworks! into my Pod file there happened errors on my other Pods, for this reason I wanted include your pod manually. :)

**Comment by andreamazz** [comment]
:+1: 
Let me know if you need further assistance.

**Comment by alejouribesanchez** [comment]
@Shamsiddin Other option for objective-c projects is use this version: https://github.com/alejouribesanchez/ScrollHideNavigationController
