### ISSUE TITLE
Doesn't work correctly with In-Call Status Bar

### ISSUE THREAD

**Issue by solomon23** [andreamazz/AMScrollingNavbar#180]
Was having issues with my project and verified the Demo project is having the same issues:

1. Open the demo in the simulator
2. Go to scroll view
3. Scroll down to make the bar minimize
4. click Command-Y
5. notice it's weird
https://www.dropbox.com/s/sl2piq99bp0wzib/Screenshot%202016-02-05%2014.13.52.png?dl=0
6. Scroll around
7. notice it's still doing weird stuff
https://www.dropbox.com/s/2831ky07dpe629e/Screenshot%202016-02-05%2014.14.03.png?dl=0
https://www.dropbox.com/s/ggefwgn8bbpxd5s/Screenshot%202016-02-05%2014.14.13.png?dl=0

**Comment by andreamazz** [comment]
Confirmed. I'm pretty sure I tested this, so this might be a regression :/
I'll try to fix this as soon as possible.

**Comment by Igor-Palaguta** [comment]
Hello, is there any solution or workaround for this

**Comment by Igor-Palaguta** [comment]
When status bar is in call status rootViewController has on iPhone 6s plus frame: (0.0, 20.0, 414.0, 716.0), when not in call state it has frame: (0.0, 0.0, 414.0, 736.0).

So we should take into account that controller is moved to bottom, so we minus controller's minY in window coordinates

var statusBarHeight: CGFloat {
        return UIApplication.sharedApplication().statusBarFrame.size.height - self.view.convertRect(self.view.bounds, toView: nil).minY
    }

**Comment by Igor-Palaguta** [comment]
I can prepare PR, please approve

**Comment by andreamazz** [comment]
Hi @Igor-Palaguta 
Thanks, this fixes the issue. I integrated the change in the latest commit.
