### ISSUE TITLE
scrollingNavbarDelegate retained too long

### ISSUE THREAD

**Issue by SpiraMira** [andreamazz/AMScrollingNavbar#183]
Noticed an annoying retain cycle after my ScollingNavigationViewController was dismissed. The scrollingNavbarDelegate was retained too long and my deinit was not being called in a timely fashion (in my opinion).  When i declare it weak in scollingNavigationController.swift the controller deinit's as (and when) expected (as I am dismissing it)

suggest:
    public **weak** var scrollingNavbarDelegate: ScrollingNavigationControllerDelegate?

Thanks.

**Comment by andreamazz** [comment]
I can't believe I missed this mistake, thanks for the heads up. 
Fixed in `2.0.11`
