### ISSUE TITLE
CollectionView Scrolling Problem

### ISSUE THREAD

**Issue by mcyaiahua** [andreamazz/AMScrollingNavbar#184]
Hi,

I'm trying to implement collectionView your codes into my project(UIViewController -> CollectionView) . But when i scrool up or down, screen scrool doesnt work properly. Sometimes scrolling work properly but sometimes doesnt work.

How can i fix this problem ?

Or

If you have a sample project using collenctionView, could you send me please ?

Thanks.

**Comment by burakyldz** [comment]
Same problem here. I am waiting to fix this problem.

**Comment by andreamazz** [comment]
I'm adding a collection view in the demo app. The implementation is identical to the other views, but there is one catch: the translucent bar breaks the scrolling. The weird thing is that sometimes it works fine. 
I'll do some more digging.

**Comment by mcyaiahua** [comment]
Thanks.Same problem here

**Comment by brandonroth** [comment]
I'm having this issue as well and tracked it down to `ScrollingNavigationController.swift` line 323.  It appears that simply calling `setContentOffset` there with any value doesn't cause the content offset to actually change and instead causes the bouncing of the scrollview to break.  

I was able to replicate this reliably in a small sample project with a plain UICollectionView implementation so it appears to be a bug in UIKit.

**Comment by andreamazz** [comment]
Hey @brandonroth 
Thank you for the forensic work on this issue 👍 
Did you file a radar?

**Comment by toseefkhilji** [comment]
Same problem here
