### ISSUE TITLE
Example of custom header + navigation bar hide animation

### ISSUE THREAD

**Issue by jazz-mobility** [andreamazz/AMScrollingNavbar#187]
Hello, can you please add Example of custom header/view + navigation bar hide animation

**Comment by alexvbush** [comment]
+1

**Comment by GuappaApps** [comment]
+ 2

I have added an extra UIView and want to pin the constraint to the Navbar or add the subview to the NavBar but neither work. Open to any ideas..

**Comment by jazz-mobility** [comment]
I got a work around to it, here is my code.
        self.shyNavBarManager.scrollView = productCollectionView
        filterView.translatesAutoresizingMaskIntoConstraints = true
        filterView.frame = CGRectMake(0, 0, CGRectGetWidth(self.view.bounds), 44)
        self.shyNavBarManager.extensionView = filterView

Filterview is a view with 44 height and top/left/right constraints on the storyboard.
I am removing constraints here and assigning it a frame. Works fine in my case.

**Comment by GuappaApps** [comment]
Jazz-Mobility...

Glad to know you've found a solution, but can you share a bit more. What have you defined shyNavBarManager as...and the same for productCollectionView. Thanks!

**Comment by jazz-mobility** [comment]
<img width="360" alt="screen shot 2016-03-13 at 23 27 58" src="https://cloud.githubusercontent.com/assets/2293605/13731818/4a3dd540-e973-11e5-8826-c70fbaa28945.png">

Yea sorry for incomplete description.
So filterview is the complete view which includes two buttons filter and sort, It has constraints of top left right to edges and height 44. Top constraint is 0 with top layout guide.

productCollectionView is the collection view which also has all edges fixed with 0 constraint. Top constraint is 0 with top layout guide.

Now if you use the above code, it should work fine.

**Comment by GuappaApps** [comment]
Hmm and what about the skyBarManager I mentioned? Extension view on a UINavigationController doesn't exist. Have you subclassed this elsewhere?

Also is the collectionView over or under the filterView?

**Comment by jazz-mobility** [comment]
Ooops Sorry for all the confusion, I did all this last week, I am using different component now, which is extension of AMScrollingNavBar library. - https://github.com/telly/TLYShyNavBar

Really sorry for all the confusion, seems like I am still into my weekend parties :palm_tree:

**Comment by GuappaApps** [comment]
Thanks so much @jazz-mobility. I was trying to customise this library but now you have shown me that there is one out there perfectly ready and suitable for what I want to do. It's a fantastic framework so thanks for pointing me in the direction of it, in the midst of the confusion! I've got it to work and it runs beautifully. Sorry @andreamazz - you can ignore my feature requests for now.

**Comment by zongren** [comment]
nice work around

**Comment by andreamazz** [comment]
If anyone else needs a view, or multiple views pinned, the feature is now available in `3.2.0` https://github.com/andreamazz/AMScrollingNavbar#followers
