### ISSUE TITLE
Can't get delegate methods to be called

### ISSUE THREAD

**Issue by jasonnoahchoi** [andreamazz/AMScrollingNavbar#189]
In my current Swift project, I can't get any of the delegate methods to be called.

In my ViewController:
    
    class ViewController: ScrollingNavigationControllerDelegate {
        // setup tableview & properties, etc

        func scrollingNavigationController(controller: ScrollingNavigationController, didChangeNavigationBarFrame frame: CGRect) {
             print("Change")
        }
    
        func scrollingNavigationController(controller: ScrollingNavigationController, didChangeState state: NavigationBarState) {
            if state == .Collapsed {
                print("Collapsed")
            } else if state == .Expanded {
                print("Expand")
            } else {
                print("Scroll")
            } 
        }
     }

None of these statements ever print. Any help would be appreciated.

**Comment by andreamazz** [comment]
Did you set the delegate property?
```swift
        if let navigationController = self.navigationController as? ScrollingNavigationController {
            navigationController.scrollingNavbarDelegate = self
        }
```

**Comment by jasonnoahchoi** [comment]
Ah nice! So silly. Good looking out @andreamazz. Closing issue.
