### ISSUE TITLE
Customise "Push Threshold" of disappearing NavBar

### ISSUE THREAD

**Issue by GuappaApps** [andreamazz/AMScrollingNavbar#190]
As I had earlier mentioned on twitter, it would be fantastic if we could further customise when the NavBar disappears, by being able to amend or add a positive / negative integer so that the NavBar scrolls up earlier, if users desire. I have amended the delay of 50, but I cannot add a negative integer to make a difference...it still pushes up too late.

Would love any help, thanks!

`
         override func viewDidAppear(animated: Bool) {
         super.viewDidAppear(animated)
         if let navigationController = self.navigationController as? ScrollingNavigationController {
            navigationController.followScrollView(tableView, delay: 0.0)
        }
    }`

**Comment by andreamazz** [comment]
Ok, I see what you mean, it's a bug really. When the delay is 0 it should start scrolling right away. I'll try to fix it as soon as possible.

**Comment by andreamazz** [comment]
Should be fixed now.
