### ISSUE TITLE
UIViewController with TableView doesn't want to implement ScrollToTop

### ISSUE THREAD

**Issue by GuappaApps** [andreamazz/AMScrollingNavbar#191]
When implementing this with a tableview within a ViewController rather than a traditional UITableViewController, the ScrollViewShouldlScrollToTop refuses to be called. The view is embedded within a navigation controller and all other functionality works but when tapping the status bar, it 1) won't jump to the first cell like the demo shows and 2) won't obviously display the NavigationBar again.

Wondering whether I've missed some code out but I'm calling the functions that have been suggested. However the scrollViewShouldScrollToTop cannot be inserted as an override function (as it does not override anything), only a normal function. Perhaps this is the culprit?

**Comment by andreamazz** [comment]
Terribly sorry about the delay, but yes, that's the culprit. That method is an override of `UIScrollviewDelegate`.
