### ISSUE TITLE
UITextView in ScrollView

### ISSUE THREAD

**Issue by Anhnh** [andreamazz/AMScrollingNavbar#192]
Firstly, Thank you for the great library!
I was found a problem. When i add TextView have long content in Scrollview. I scroll TextView and the Navigation bar scroll follow it. So can you help me resolve this bug.

**Comment by andreamazz** [comment]
Can you post a sample showing the issue?

**Comment by andreamazz** [comment]
I guess not. Feel free to reopen if needed.
