### ISSUE TITLE
ScrollingNavbar+Size Errors

### ISSUE THREAD

**Issue by JKINGH** [andreamazz/AMScrollingNavbar#195]
I have added the three files to my project ScrollingNavigationController, ScrollingNavigationViewController & ScrollingNavbar+Sizes. However for the last files I get the following errors. 

Is there something I am doing wrong ? Do I not just add the three files and change the class of the UINavigationController then use the methods ? 

<img width="865" alt="screen shot 2016-03-23 at 18 18 27" src="https://cloud.githubusercontent.com/assets/5117290/13996032/d57a3268-f123-11e5-9a4d-0822e8215429.png">

**Comment by andreamazz** [comment]
Looks like your project isn't importing UIKit. How are you importing this? In what kind of project?

**Comment by andreamazz** [comment]
I've added an import to UIKit in the latest version, this should solve this issue.
