### ISSUE TITLE
Module file was created by an older version of the compiler rebuild and try again

### ISSUE THREAD

**Issue by jameszoh** [andreamazz/AMScrollingNavbar#196]
Problem occur after updating xcode to 7.3.

Problem happened on this line: `import AMScrollingNavbar`

`/Volumes/AppXXX/ArticleContentViewController.swift:10:8: Module file was created by an older version of the compiler; rebuild 'AMScrollingNavbar' and try again: /Volumes/AppXXX/AMScrollingNavbar.framework/Modules/AMScrollingNavbar.swiftmodule/x86_64.swiftmodule`

**Comment by andreamazz** [comment]
Hi @jameszoh 
I've updated the lib to Swift 2.2 syntax, and rebuilt it with Xcode 7.3. The new version is 2.1, let me know if it works now.

**Comment by jameszoh** [comment]
Hi @andreamazz
It works fine on 2.1.0. thx!
