### ISSUE TITLE
How to use the lib without subclassing UINavigationController

### ISSUE THREAD

**Issue by RanjitKadam** [andreamazz/AMScrollingNavbar#198]
Hello, 

firstly, the lib is awesome, secondly, I have already subclassed my UINavigationController with other 3rd party lib. So if I subclass with your lib, my code breaks. So how can we work out with this.

**Comment by andreamazz** [comment]
Hi @RanjitKadam 
With the Swift rewrite I decided to implement it as a subclass of UINavigationController to simplify the code. The Objective-C version was an extension of UIViewController, so you might give that a try. You'll find the previous version with the tag `1.5.1`.

**Comment by RanjitKadam** [comment]
Hey @andreamazz 
Thanks, but my project is in swift. So how can the objective-C version work out?

**Comment by andreamazz** [comment]
You can use Objective-C libs with Swift. If you use CocoaPods or Carthage it's pretty straightforward.

**Comment by RanjitKadam** [comment]
ok let me try and get back to you
