### ISSUE TITLE
nav bar items not fading out

### ISSUE THREAD

**Issue by flakdeezy** [andreamazz/AMScrollingNavbar#2]
Having a issue with my nag bar items still appearing a few pixels in the status bar and not getting the ease out animation when scrolling up

**Comment by iceNuts** [comment]
Hi there,

I read through the whole issue and it looks like ```refreshNavbar``` is the key. However, there is no more such method now. Then what else can I use?

Thanks.

**Comment by andreamazz** [comment]
I'm drawing a blank on why it was removed, I'll be honest, but the same code should be called with the `showNavbar` and `hideNavbar`. So:
```objc
- (void)viewWillAppear:(BOOL)animated{
    [self refreshNavbar];
}
```
