### ISSUE TITLE
Cannot subclass a class with objc_subclassing_restricted attribute

### ISSUE THREAD

**Issue by richy486** [andreamazz/AMScrollingNavbar#202]
Can't use with objective-c project when we have to subclass the ScrollingNavigationController.

**Comment by andreamazz** [comment]
Not much I can do about it. You can however use version `1.5.1` where the component was implemented as a UIViewController category.

**Comment by bernikowich-cedoni** [comment]
You should add this to README because currently you have following description:
```
Objective-C

- (void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];

    [(ScrollingNavigationController *)self.navigationController followScrollView:self.tableView delay:50.0f];
}
```

**Comment by andreamazz** [comment]
That snippet of code is correct, provided that the navigation controller is a subclass of `ScrollingNavigationController`, ass tated in the readme.
