### ISSUE TITLE
Good way to listen for navigation controller state?

### ISSUE THREAD

**Issue by stevejcox** [andreamazz/AMScrollingNavbar#203]
Great library!

I have a button at the bottom of the view I'd like to hide in a similar fashion to how the navigation controller hides. So on scroll the nav bar hides + the button moves off the bottom of the screen.

Are there any events I could tap into without having to create new gesture handlers?

**Comment by andreamazz** [comment]
You can provide a delegate method to animate out of the view the button:
https://github.com/andreamazz/AMScrollingNavbar#scrollingnavigationcontrollerdelegate
