### ISSUE TITLE
Titleview alpha is not updating successfully.

### ISSUE THREAD

**Issue by OEA** [andreamazz/AMScrollingNavbar#207]
Hey @andreamazz thank you for this amazing lib. I faced an issue when I present another view controller It cannot update my navigationItem.titleView until scroll.

(I also added button to titleView)

So I found the problematic codes but I don't know that it may break the other scenarios.

When you decide to dismiss or open a new view controller, viewWillDisappear will be called when the view is dismissed, covered or otherwise hidden. So problem arrives here, I want to open new view controller after showing navbar. 

So I added this line to inside showNavbar

`self.topViewController?.navigationItem.titleView?.alpha = 1`

What is your thinking about this problem ?

Kind Regards.

**Comment by andreamazz** [comment]
Hi @OEASLAN 
Can you post a simple sample project showing this issue to help me debug it?

**Comment by Anders123fr** [comment]
I had the same problem when showing a ViewController modally on top of the ViewController using AMScrollingNavBar. 
Putting the line of code from above inside my `viewWillDisappear()` after calling `showNavbar()` makes the titleView visible

**Comment by sssbohdan** [comment]
I had the same issue, the problem was in my code : 
```
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        
        navigationController?.setNavigationBarHidden(true, animated: false)
        navigationController.showNavbar(animated: true)
    }
```
Then place call of `showNavbar` before `setNavigationBarHidden` and everything start working.
