### ISSUE TITLE
Library not loaded on iPhone 4S simulator 

### ISSUE THREAD

**Issue by AndreaStevanato** [andreamazz/AMScrollingNavbar#208]
Hi, i have this crash when i run an application with the iphone 4s simulator

`dyld: Library not loaded: @rpath/AMScrollingNavbar.framework/AMScrollingNavbar
  Referenced from: /Users/andrea/Library/Developer/CoreSimulator/Devices/2A9CE70F-56F5-4D11-A419-1C5D0B132669/data/Containers/Bundle/Application/D6E3E079-61CA-4569-BC43-690DCE9CB631/MYApp.app/MYApp
  Reason: no suitable image found.  Did find:
    /Users/andrea/Library/Developer/CoreSimulator/Devices/2A9CE70F-56F5-4D11-A419-1C5D0B132669/data/Containers/Bundle/Application/D6E3E079-61CA-4569-BC43-690DCE9CB631/MYApp.app/Frameworks/AMScrollingNavbar.framework/AMScrollingNavbar: mach-o, but wrong architecture
    /Users/andrea/Library/Developer/CoreSimulator/Devices/2A9CE70F-56F5-4D11-A419-1C5D0B132669/data/Containers/Bundle/Application/D6E3E079-61CA-4569-BC43-690DCE9CB631/MYApp.app/Frameworks/AMScrollingNavbar.framework/AMScrollingNavbar: mach-o, but wrong architecture
    /Users/andrea/Library/Developer/CoreSimulator/Devices/2A9CE70F-56F5-4D11-A419-1C5D0B132669/data/Containers/Bundle/Application/D6E3E079-61CA-4569-BC43-690DCE9CB631/MYApp.app/Frameworks/AMScrollingNavbar.framework/AMScrollingNavbar: mach-o, but wrong architecture
`

**Comment by andreamazz** [comment]
Hey @AndreaStevanato 
The demo app works fine on the iPhone 4s simulator, so I'm guessing it's a configuration issue on your side. How are you integrating the library in your project?

**Comment by andr3a88** [comment]
I'm using Cocoapods. With a physical 4s the app works fine.

**Comment by AndreaStevanato** [comment]
I'm using Cocoapods. With a physical 4s the app works fine

**Comment by andreamazz** [comment]
I'm not sure how I'm supposed to debug an issue that can't be reproduced. Please provide a sample project showing the issue.
