### ISSUE TITLE
Nav Bar gets Black when Scrolling

### ISSUE THREAD

**Issue by florinzf** [andreamazz/AMScrollingNavbar#210]
Thanks for the library. I've been using AMScrollingNavbar successfully for the last period of time. However, now I added support for empty views using this library: DZNEmptyDataSet*.
By doing this, whenever I show an empty view, then load some data in the table, the navigation bar gets black when scrolling. Whenever it finishes scrolling (it fully disappears or appears), everything gets back to normal. Any ideas?

Normal Navigation Bar:
![033999ec-5640-11e6-99e4-d3afc8806a62](https://cloud.githubusercontent.com/assets/15258293/17742813/2fddd418-64aa-11e6-9a83-b330715a4b9c.jpg)

Navigation Bar When Scrolling:
![031405f6-5640-11e6-9fce-c4b829398164](https://cloud.githubusercontent.com/assets/15258293/17742826/38021ba4-64aa-11e6-8afc-cef79f93ca20.jpg)

**Comment by andreamazz** [comment]
Hey @florinzf 
Can you provide a simple demo project showing this issue to help me debug it?

**Comment by florinzf** [comment]
Hey. I'm still struggling to replicate it in a different project. Turns out, simply adding the DZNEmptyDataSet library wasn't enough, although this is what triggered the problem in the main project.

In the meantime, if you have any ideas on what I could try changing, that'd be great. Thanks!

**Comment by andreamazz** [comment]
I never used DZNEmptyDataSet. On top of my mind it might be something related to a gesture recognizer (if DZNEmptyDataSet has its own to implement a pull to refresh or whatnot).
But it's tricky without a project to debug :)

**Comment by khaskheli24** [comment]
showing black navigation bar while moving up ui table view controller

**Comment by khaskheli24** [comment]
help

**Comment by andreamazz** [comment]
Please @khaskheli24 report a proper issue with a proper description, and if possible a working sample for me to debug.

**Comment by florinzf** [comment]
As an update on this, the problem became permanent when I added a custom refresh control. 
Adding the same refresh control in a separate project, did not help replicating the issue... I had to deactivate the scrolling effect all together. 
I spent quite some time trying to debug this with no luck. Any suggestions on what I could look at? Any flags to put in the code?

**Comment by brianlenz** [comment]
We were having the same issue (or at least the same symptom ;). We have a really simple ScrollingNavigationViewController (essentially just an empty controller) that contains a ScrollingNavigationViewController which has a WKWebView in it. We initialize the WKWebView frame to the size of the default view's frame (so it fills the entirety of the visible space below the nav bar). The black bar was appearing since the size of the WKWebView was not being updated as the nav bar scrolls off the screen. In other words, the black bar that appears is vacant, un-rendered space without a view.

In our case, the fix was easy: we just had to add the WKWebView itself as a follower:

```
if let navigationController = navigationController as? ScrollingNavigationController {
    navigationController.followScrollView(self.webView.scrollView, delay: 50.0, scrollSpeedFactor: 1, followers: [self.webView])
}
```
With that in place, the WKWebView now properly scrolls "with" the nav bar.

@andreamazz are you able to confirm this is the proper approach to address the problem in this scenario?

@florinzf perhaps this information is helpful to your scenario?

**Comment by andreamazz** [comment]
@brianlenz 
Thanks for sharing your experience, that's really helpful. Yeah, I think that's the right approach, it'd be worth updating the sample project for the webview using this solution.

**Comment by divij1997** [comment]
this doesn't work properly. you will get a black bar issue in some setups. Don't add a follower. 
keep your code as 
navigationController.followScrollView(self.webView.scrollView, delay: 50.0)

The fix I have is that I set the tableview/webview top constraint to superview, then enable adjust scroll insets. Have extended under top and bottom bars checked too. This should fix everything.

**Comment by brianlenz** [comment]
Yeah, you're right. PR #239 fixed this for us, as well, by supporting WKWebView in addition to UIWebView.

**Comment by divij1997** [comment]
It'd be great if you guys could create a small debugging post for swift 3. I wasted a lot of time with weird inset bugs.

**Comment by divij1997** [comment]
So I'm still having a bug with wkwebview - now having a black/white bar underneath. any ideas?

**Comment by nadagamal** [comment]
I have the same issue :(

**Comment by ArthurBodrov** [comment]
`extendedLayoutIncludesOpaqueBars = true` in viewDidLoad and `.backgroundColor = <your color>` in your navigationBar view solved this issue for me.
