### ISSUE TITLE
Not working: if let navigationController = self.navigationController as? ScrollingNavigationController {

### ISSUE THREAD

**Issue by unittesting0** [andreamazz/AMScrollingNavbar#212]
```
if let navigationController = self.navigationController as? ScrollingNavigationController {
            navigationController.followScrollView(tableView, delay: 50.0)
        }else{
            print("ScrollingNavigationController NOT LOADED")
        }
```

I always get ScrollingNavigationController NOT LOADED.

What should be the problem?

**Comment by andreamazz** [comment]
You are probably using a plain UINAvigationController instead of a ScrollingNavigationController

**Comment by unittesting0** [comment]
Thanks, this worked.
Now if the navigation bar is collapsed and I go to back to the first viewcontroller I get black navigation bar.

**Comment by andreamazz** [comment]
https://github.com/andreamazz/AMScrollingNavbar#handling-navigation

**Comment by unittesting0** [comment]
> https://github.com/andreamazz/AMScrollingNavbar#handling-navigation
It worked.

Now at the bottom I get black (the size of this black bottom is same as navigationbar)

**Comment by unittesting0** [comment]
I have to close this because didn't know how to solve unfortunately, it is the tabbar which i wanted to hide but nevermind.
