### ISSUE TITLE
Hide NavigationBar when scrolling down ?

### ISSUE THREAD

**Issue by TunaYangSkey** [andreamazz/AMScrollingNavbar#216]
First I want to say that I love this library. It's easy to use and light weight compared to other similar libraries. 

Currently it only hides the navigation bar when you scroll up the screen, i.e. going down to the bottom of the ScrollView/TableView. I am wondering if there is a way to hide the navigation bar when you scroll down the screen. Basically what I want is hiding the navigation bar whenever the user scrolls the screen.

**Comment by andreamazz** [comment]
Hey @TunaYangSkey 
Thanks for the kind words.  
Mmm... I get what you mean, I never thought about it, but it should be doable easily. I'll do it in the next few days.
