### ISSUE TITLE
showNavbar with time interval option?

### ISSUE THREAD

**Issue by TunaYangSkey** [andreamazz/AMScrollingNavbar#217]
Currently the function "showNavbar" doesn't have an argument of time delay and the function itself by default delays 0.1 sec. I am wondering if in the future this function can take the time delay argument so that we have more flexibility to change how fast the navigation bar will show up?

**Comment by andreamazz** [comment]
Hey @TunaYangSkey 
I've added an optional parameter in `showNavbar(_:duration:)` and `hideNavbar(_:duration:)`
