### ISSUE TITLE
New states for expanding and collapsing

### ISSUE THREAD

**Issue by eliasbagley** [andreamazz/AMScrollingNavbar#220]
I need extra states for Expanding and Collapsing, to react when the navigation bar is about to show and hide. 

Or, another delegate method that alerts when states are about to change. 

I can submit a MR for this - which approach would you prefer?

**Comment by andreamazz** [comment]
Hi @eliasbagley 
A PR would be great.

**Comment by eliasbagley** [comment]
@andreamazz turns out that's not quite the API I need. Basically, I have a bottom bar in my UI that I want to hide simultaneously when the navbar hides.

I think instead the API that I need is an optional delegate method that informs on the navbars current offset or % completion. This way I can hook into this API and if the user slowly drags, both top and bottom bars can start to gradually animate at the same time.

What do you think?

**Comment by andreamazz** [comment]
Sounds like a good addition, the percentage would be great. Can you hack it in a PR?

**Comment by andreamazz** [comment]
The percentage is now in master.
