### ISSUE TITLE
Apply for UIWebview

### ISSUE THREAD

**Issue by leminhtuan2015** [andreamazz/AMScrollingNavbar#221]
It seem not working with UIwebview?

I looking for Navbar will hide when scrolling a UIWebview. Can you please give me any ideal.

Thank sir so much!

**Comment by andreamazz** [comment]
Hey @leminhtuan2015 
The sample project has a section with the UIWebView, so...  
If you implemented it the same way and are still having issues, please post the code that you are using.

**Comment by andreamazz** [comment]
Closing this, feel free to reopen if you need further assistance.
