### ISSUE TITLE
When the navbar state is collapsed, pressing the point(about below statusBar 4px, margin left 15px) also can pop back. 

### ISSUE THREAD

**Issue by YioMidd** [andreamazz/AMScrollingNavbar#223]
Then back to previous controller, the navbar changes back to original appearance flickeringly.
I found that in the sample code.
Is it a bug?

**Comment by andreamazz** [comment]
Yep. Nice catch @YioMidd 
I'll see if I can fix it.

**Comment by andreamazz** [comment]
Checkout latest commit for a fix.
