### ISSUE TITLE
navbar pop problem with gesture

### ISSUE THREAD

**Issue by 2016321** [andreamazz/AMScrollingNavbar#225]
dear developer .the navbar was hidden. whereafter, i pop the controller with gesture.there are some problem over the navbar. sorry,i don't know how to describe this issue

**Comment by andreamazz** [comment]
> i don't know how to describe this issue

It's pretty hard to fix an issue with no description. Can you reproduce the issue in the sample project? Or maybe provide a project showing the issue.

**Comment by 2016321** [comment]
When I use gestures pop but i cancel halfway，the navbar‘s backgroundcolor will change to  previous navbar' color

**Comment by andreamazz** [comment]
That's not related to the library though.  
I fixed the issue in the sample project anyway, checkout the latest commit.
