### ISSUE TITLE
I want to move up toolbar with navigation.

### ISSUE THREAD

**Issue by mengheangrat** [andreamazz/AMScrollingNavbar#226]
<img width="464" alt="screen shot 2016-12-29 at 4 49 03 pm" src="https://cloud.githubusercontent.com/assets/10340553/21541150/c88c1152-cde6-11e6-8028-bc40c0fadbc2.png">

**Comment by andreamazz** [comment]
Hey @mengheangrat 
Check out the latest version, I've added an extra parameter to the `followScrollView` call, named `followers`. Provide your toolbar in the array, like so:
```swift
navigationController.followScrollView(tableView, delay: 50.0, followers: [toolbar])
```

Check out the sample.
