### ISSUE TITLE
Unable to hide NavBar when viewWillAppear

### ISSUE THREAD

**Issue by romainbiard** [andreamazz/AMScrollingNavbar#227]
I would like to have the opportunity to start with the navbar hidden when a UICollectionViewController is first displayed.
To do so, I've put this code below but it does not work ;-(
```swift
override func viewWillAppear(_ animated: Bool) {
    super.viewWillAppear(animated)
    if let navigationController = self.navigationController as? ScrollingNavigationController {
        navigationController.followScrollView(collectionView, delay: 20.0, scrollSpeedFactor: 3)
        navigationController.hideNavbar()
    }
}
```
I've a sample code if you want so don't hesitate ;-)
Thanks.

**Comment by andreamazz** [comment]
Hi @romainbiard 
Sure, sample code is always welcome

**Comment by romainbiard** [comment]
The first tab is an integration with `UIViewController` + `UICollectionView` in it.
The second is an integration with `UICollectionViewController`

I repro the issue on both.
Thanks !

**Comment by andreamazz** [comment]
Ok, looks like it's a bug with both the delay and the scrolling factor
Try this code:

```swift
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        if let navigationController = self.navigationController as? ScrollingNavigationController {
            navigationController.followScrollView(collectionView)
        }
    }

    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        if let navigationController = self.navigationController as? ScrollingNavigationController {
            navigationController.hideNavbar(animated: false)
        }
    }
```

**Comment by romainbiard** [comment]
Thanks a lot, it works !
I'll probably make a PR moving the scrollSpeedFactor at higher level since it seems to affect other APIs like this.

**Comment by andreamazz** [comment]
Awesome, thanks
