### ISSUE TITLE
Scrolling horizontally within a cell's scrollView leads to navigationBar scrolling

### ISSUE THREAD

**Issue by kubatruhlar** [andreamazz/AMScrollingNavbar#230]
A `tableView` cell has a `scrollView` as a `subview`. When I'm scrolling that `scrollView` horizontally but move a little bit up/down, `tableView` is not moving, but `navigationBar` is. Even when I try to set your `scrollingEnabled` to false in `scrollViewDidScroll`.

**Comment by andreamazz** [comment]
Hey @kubatruhlar 
This might be tricky, I would add a gesture recognizer in the whole view, if the gesture starts on the scrollview, disable the scrolling, and re-enable it when the gesture ends. `scrollViewDidScroll` might be too late down the chain.

**Comment by Igor-Palaguta** [comment]
@kubatruhlar 
I reassigned ```gestureRecognizer``` delegate after ```followScrollView```. And then filter gestures from horizontal scrollable views, e.g. ```UICollectionView```

```
   var scrollingNavigationController: ScrollingNavigationController? {
      return self.navigationController as? ScrollingNavigationController
   }

   func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldRecognizeSimultaneouslyWith otherGestureRecognizer: UIGestureRecognizer) -> Bool {
      return !(otherGestureRecognizer.view is UICollectionView)
   }

   func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldReceive touch: UITouch) -> Bool {
      return self.scrollingNavigationController?.scrollingEnabled ?? false
   }
```
