### ISSUE TITLE
Hide UITabbar on scrolling

### ISSUE THREAD

**Issue by tamanyan** [andreamazz/AMScrollingNavbar#232]
Hi thank you for this great lib.
I want to a feature that hiding UITabbar on scrolling.

Please consider it.

**Comment by derick182** [comment]
Maybe found a solution. I'll PR as soon as I can. Hope You will like it @andreamazz.
and Thanks for the job you have done and you keep doing 🇮🇹

**Comment by derick182** [comment]
Added PR #258

**Comment by andreamazz** [comment]
Thank you @derick182 for your contribution. I've release 3.4.0 with this feature.

Cheers
