### ISSUE TITLE
Use of undeclared type ScrollingNavigationController

### ISSUE THREAD

**Issue by Jasperav** [andreamazz/AMScrollingNavbar#233]
I followed every step, but I get this error Use of undeclared type ScrollingNavigationController:

        if let navigationController = self.navigationController as? ScrollingNavigationController {
            navigationController.followScrollView(tableView, delay: 50.0)
        }

Is there no need for import module? If so, how and what is this module called?

**Comment by brianlenz** [comment]
You need:

```
import AMScrollingNavbar
```
