### ISSUE TITLE
Hide NavigationBar on/before load

### ISSUE THREAD

**Issue by brianlenz** [andreamazz/AMScrollingNavbar#235]
Is there any way to hide the `NavigationBar` before the view has fully loaded? For our scenario, we are looking to have the nav bar generally collapsed, but become available in cases where appropriate.

As it stands right now, when the `ScrollingNavigationViewController` loads, we are doing a sequence of:

```
followScrollView()
hideNavBar()
stopFollowingScrollView()
```

But there are a variety of issues with this approach, including:

* Timing of view updates seems to prevent the `hideNavBar()` from actually succeeding in hiding the nav bar
* `stopFollowingScrollView()` first calls `showNavBar()` which means that the hideNavBar would be un-done

For our scenario, we are using the nav bar to present a simple back button, but on the first view load, there should be no back button since there is nowhere to go back to. Because of this, we need to hide the `NavigationBar` on initial load.

Thanks in advance for any tips or advice you can offer!

**Comment by andreamazz** [comment]
Hey @brianlenz 
Try with:
```swift
            navigationController.stopFollowingScrollView(showingNavbar: false)
            navigationController.expandOnActive = false
```

I did a quick test, and doing this in the viewDidLoad seems to be working.

**Comment by brianlenz** [comment]
Hi @andreamazz, thanks much for a quick follow-up here!

We've given your suggestion a shot by adding the code to `viewDidLoad` in our `ScrollingNavigationViewController` equivalent, but it doesn't seem to work.

We are setting `expandOnActive` to false in the `ScrollingNavigationController` in `viewWillAppear`.

Then, in the `ScrollingNavigationViewController`'s `viewWillAppear`, we call:

```
navigationController.followScrollView(self.webView.scrollView, delay: 50.0, scrollSpeedFactor: 1, followers: [self.webView])
```

Then, in `ScrollingNavigationViewController`'s `viewDidLoad`, we call:

```
navigationController.hideNavbar(animated: true)
navigationController.stopFollowingScrollView(showingNavbar: false)
```

Nevertheless, the nav bar is _not_ hidden on initial load; it remains persistently displayed. Is there some kind of race condition perhaps between `hideNavBar` and `stopFollowingScrollView` (e.g. UI rendering delays from `UIView.animate()`) that could be causing issues?

FWIW, I tried forking the library and doing something similar to the change you made in 841a81f09be6053c0ec3540bc8127bd403954f3e, and it didn't seem to be sufficient to get the nav bar hiding properly on load.

Any ideas?

**Comment by brianlenz** [comment]
@andreamazz, we've decided to abandon the idea of hiding the nav bar on load for consistency. It seems to be causing a lot of issues, and I'm not seeing a simple way forward here, so you can consider this closed for now.

Thanks again!
