### ISSUE TITLE
expandOnActive not working?

### ISSUE THREAD

**Issue by brianlenz** [andreamazz/AMScrollingNavbar#236]
We are setting `expandOnActive` to false, but it seems every time the app enters the foreground, the navigation bar is expanded (even when previously collapsed). If my interpretation is correct, when `expandOnActive` is false, the navigation bar should remain in its current expanded/collapsed state when brought back into the foreground. Am I missing something?

Thanks!

**Comment by brianlenz** [comment]
Hmm, this doesn't seem to be working. We have a scenario where we have stopped following scrolling and the nav bar is hidden (i.e. it won't appear). When we background the app and bring it back into the foreground, the nav bar appears (though it should not). Scrolling is still disabled at this point, so the nav bar remains fixed on the screen.

Additionally, in the scenario where the navigation view is following scrolling, if the nav bar is collapsed and you background/foreground the app, the nav bar appears at first, and then hides. Is there a way to just keep it hidden when the app is brought back to the foreground so it doesn't have the undesired side effect of appearing and then disappearing?

**Comment by andreamazz** [comment]
> Hmm, this doesn't seem to be working. We have a scenario where we have stopped following scrolling and the nav bar is hidden (i.e. it won't appear). When we background the app and bring it back into the foreground, the nav bar appears (though it should not). Scrolling is still disabled at this point, so the nav bar remains fixed on the screen.

Can you breakpoint the library at line 235 and check the value of `previousState` when the app becomes active?
It should be `.collapsed`

> Additionally, in the scenario where the navigation view is following scrolling, if the nav bar is collapsed and you background/foreground the app, the nav bar appears at first, and then hides. Is there a way to just keep it hidden when the app is brought back to the foreground so it doesn't have the undesired side effect of appearing and then disappearing?

Nope, the bar is shown by UIKit, there's not much to do in that regard.

**Comment by brianlenz** [comment]
Thanks for the follow-up, @andreamazz!

> Can you breakpoint the library at line 235 and check the value of previousState when the app becomes active?
>It should be `.collapsed`

So, that line actually isn't being hit. I think the issue is that since we have stopped following scrolling, did `didBecomeActive` observer is no longer listening, right?

> Nope, the bar is shown by UIKit, there's not much to do in that regard.

OK, that's too bad.

**Comment by brianlenz** [comment]
I added a workaround to test this by bypassing the removal of the `UIApplicationDidBecomeActive` observer in `stopFollowingScrollView`. With the observer still in place, `didBecomeActive` _does_ get called. The `previousState` is properly set to `.collapsed`, yet the nav bar still remains visible after execution.

The issue then is the first line in `hideNavbar`:

```
guard let _ = self.scrollableView, let visibleViewController = self.visibleViewController else { return }
```

Since we're not following scrolling, `self.scrollableView` is `nil`, and so `hideNavbar` short circuits without doing anything.

**Comment by brianlenz** [comment]
As I mentioned in #235, we are no longer going to hide the nav bar, so this is no longer an issue for us. We're just going to always have the nav bar follow scrolling, which I think is more in line with the intent of your library here.

Thanks!

**Comment by andreamazz** [comment]
Yeah, the hidden navbar can be achieved, but it requires some changes to the whole flow of the library.

**Comment by pablogeek** [comment]
@andreamazz How is this going? I'm having the same issue, my bar expands when I push other view controller
