### ISSUE TITLE
Wrong scrolling behaviour of UICollectionView in iOS 10 

### ISSUE THREAD

**Issue by iAppDeveloper88** [andreamazz/AMScrollingNavbar#237]
In iOS 10 something might have changed in CollectionViews. Starting the provided demo with iOS 10.2 breaks the scrolling of UICollectionViews. UITableView works as it should in iOS 10.
UICollectionView works in iOS9.
If you scroll up or down the view does not bounce. Further you can scroll down as long as you want (it does not scroll up automatically if the upper end is reached). See the screenshot attached.

To reproduce the bug just start the provided demo in an iOS 10 simulator, navigate to the CollectionView demo and scroll up or down

![simulator screen shot 01 04 2017 22 29 33](https://cloud.githubusercontent.com/assets/24368986/24582253/b8bde3e8-172b-11e7-9588-ace8cb926b82.png)

**Comment by andreamazz** [comment]
Hey @iAppDeveloper88 
Yeah, it seems to be an issue with this call:
https://github.com/andreamazz/AMScrollingNavbar/blob/master/Source/ScrollingNavigationController.swift#L340

This was a workaround, looks like a need a new one :|

**Comment by andreamazz** [comment]
Ok, I can't for the life of me remember why I implemented that method. After some testing everything looks fine. I'll push to master, let me know if that fixes your issue.

**Comment by iAppDeveloper88** [comment]
Thanks for your fast reply and the fix. Now it is working as it should.

**Comment by andreamazz** [comment]
Awesome
