### ISSUE TITLE
WebView scrolling issue: height not adjusted

### ISSUE THREAD

**Issue by brianlenz** [andreamazz/AMScrollingNavbar#238]
Now that we have the nav bar showing in all contexts, it seems to be working a lot better.

We have one final issue. When we scroll up, the nav bar hides as you expect. The problem, however, is that the WebView (and its scrollView) don't resize to fill the full height of the containing view. See screenshots:

![simulator screen shot apr 3 2017 10 29 04 pm](https://cloud.githubusercontent.com/assets/2305088/24642564/fd6e3c58-18bc-11e7-8c58-ea988b402ed0.png)
![simulator screen shot apr 3 2017 10 29 09 pm](https://cloud.githubusercontent.com/assets/2305088/24642565/fd6fc2e4-18bc-11e7-8de6-839482081408.png)

Here's the `followScrollView` call in `viewWillAppear`:

```
navigationController.followScrollView(self.webView.scrollView, delay: 0, scrollSpeedFactor: 1, followers: [self.webView])
```

Is there something we should be doing in order to get the height of the WebView and its scrollView to adjust in height when the nav bar is scrolled off the screen?

Thanks in advance for any tips you can provide!

**Comment by andreamazz** [comment]
Hey @brianlenz 
In the sample project I just do this:
```swift
navigationController.followScrollView(webView, delay: 50.0)
```

and it's working ok.

**Comment by brianlenz** [comment]
Thanks, @andreamazz; I've tried that, but the problem then is that the scrollView isn't actually followed. When we scroll the WKWebView (which is actually the WKWebView's `scrollView`), the `ScrollingNavigationController` doesn't "see" the scroll since it's internal to the WKWebView.

Digging further, I see that your `scrollView()` method in `ScrollingNavbar+Sizes.swif` only handles `UIView`, not `WKWebView`. I ran a test with:

```
  func scrollView() -> UIScrollView? {
    if let webView = self.scrollableView as? UIWebView {
      return webView.scrollView
    } else if let wkWebView = self.scrollableView as? WKWebView {
      return wkWebView.scrollView
    } else {
      return scrollableView as? UIScrollView
    }
  }
```

And that fixes the issue with scrolling detection. But, it still leaves my WKWebView undersized at the top for some reason:

![simulator screen shot apr 4 2017 10 52 40 am](https://cloud.githubusercontent.com/assets/2305088/24670954/d7d1dec4-1924-11e7-9b37-55a25a9f7d97.png)

I've got your demo code running and working with the UIWebView, so I'm going to play around with that a bit and see if I can identify any implementation differences that might be causing this. If you have any ideas, let me know!

Thanks :)

**Comment by brianlenz** [comment]
Figured the other issue out. The issue is that the `ScrollingNavigationController` and the `ScrollingNavigationViewController` both needed the _Extend Edges_ property set for _Under Top Bars_ and _Under Bottom Bars_. That got us much closer to the demo implementation, but the issue then was that the web view would extend behind the navigation bar at the top. To be honest, I can not identify why your demo implementation stays _below_ the navigation bar. My understanding is that the navigation bar will only force contents below it when it is opaque. Your demo has a translucent navigation bar, so I don't understand the difference there. I've audited just about every component I can think of in the Interface Builder and the code and can't seem to identify why the behavior is different. Any ideas on that?

In any event, for us to get things working, we needed to set the `navigationBar.isTranslucent` to false, and _then_ everything works as expected.

If you can merge the pull request above, everything will be set here.

Thanks!

**Comment by andreamazz** [comment]
> Your demo has a translucent navigation bar, so I don't understand the difference there. I've audited just about every component I can think of in the Interface Builder and the code and can't seem to identify why the behavior is different. Any ideas on that?

It's hard to tell without a sample to debug. Can you reproduce the issue in a separate project by any chance?  

I'll merge the PR right away.

**Comment by brianlenz** [comment]
We are going a different direction here, and I don't have the time right now to put together a repro case in a project.

Thanks again for your help!

**Comment by divij1997** [comment]
I'm still having issues with webView height at the bottom being incorrect.

**Comment by andreamazz** [comment]
Hey @divij1997 
Are you using the optional param `scrollSpeedFactor` mentioned in #242?

**Comment by divij1997** [comment]
Hey @andreamazz 
Sorry for the late reply. I'm no longer using that. Even when I add the wkwebview as a follower to itself, there is still an error. I've tried resetting insets. but that doesn't do anything. Any ideas. I have a custom navigation bar at the bottom, and the bottom constraint of my wkwebview is to that(well the frame that the wkwebview is set to).

**Comment by andreamazz** [comment]
Sorry @divij1997, I just saw your reply. Can you put together a sample project that mimics your configuration? I'm having a hard time reproducing this issue.

**Comment by neaped** [comment]
@andreamazz I think I got the same problem with others:

in the main.storyboard, insert a Webkit View (As Web View deprecated), set the Webkit View's top constraint to superview.top, run the app, the navigation bar will cover the Webkit View (of course, as the top constraint set to superview.top). And once I scroll the Webkit View, it will miss the top of the view

![screen shot 2018-07-02 at 8 59 17 pm](https://user-images.githubusercontent.com/3713305/42165542-edea6baa-7e3a-11e8-9b62-88ba817284b2.png)

If I set navigation bar's isTranslucent property to 'false,' then run the app, it will be fine (also in scrolling)

![screen shot 2018-07-02 at 9 01 36 pm](https://user-images.githubusercontent.com/3713305/42165598-23e55f80-7e3b-11e8-984b-3e5981200871.png)

**Comment by andreamazz** [comment]
Hi @neaped 
I've updated the demo project with a WKWebView, and it seems to be working fine. Check out [the demo code](https://github.com/andreamazz/AMScrollingNavbar/blob/master/Demo/ScrollingNavbarDemo/ViewControllers/WebViewController.swift#L27-L31), I've set it to load a remote url or a static html, both seem fine with a translucent bar.

**Comment by neaped** [comment]
Hi, @andreamazz 

Thanks for the instant reply

It's looks fine with the demo and I still have problem with my code, I add the WKWebView (custom style) programmatically rather than use the storyboard. I will check the code again and let you know the result later.

By the way, you can check the demo, in the Collection View , the "followers" function have problem with custom footer in iPhone X, the toolbar does not fully hide (Picture 1), even I change the custom footer to toolbar object (Picture 2). Even I try to change the constraint of the footer view / toolbar, it still have the same problem. Think this caused by iPhone X and extra safeare than others. (I haven't dig into the sauce code yet) 

![image](https://user-images.githubusercontent.com/3713305/42256169-410212d2-7f82-11e8-95b1-e0aeb5e89711.png)

![image](https://user-images.githubusercontent.com/3713305/42256256-c996b148-7f82-11e8-96b6-bb08f05b737d.png)

**Comment by andreamazz** [comment]
The footer is now fixed in master. I'm overhauling some of the measurements to make them more reliable, feedback is welcome.
