### ISSUE TITLE
Content offset breaks delay

### ISSUE THREAD

**Issue by iAppDeveloper88** [andreamazz/AMScrollingNavbar#240]
If you define e.g. a tableview in interface builder to fit the whole screen (as in your sample project) and set the following code
`navigationController.followScrollView(tableView, delay: 0.0, followers: [toolbar])`
the navigation bar does not scroll immediately (as you would expect).

Perhaps it is a problem in `shouldScrollWithDelta` line 263 `if contentOffset.y < 0`
If you start scrolling the y value stars at -108, so it always enters the if and returns `false` instead of `true`

You can reproduce the problem by just changing the delay to 0.0 in your tableview example.

**Comment by iAppDeveloper88** [comment]
Probably #190 seems to be related somehow

**Comment by andreamazz** [comment]
Nice catch @iAppDeveloper88 
Should be fixed now.
