### ISSUE TITLE
If BottomBar was hidden it reappears 

### ISSUE THREAD

**Issue by Shafichariri** [andreamazz/AMScrollingNavbar#245]
```swift
let someVc = SomeViewController(resource: resource)
someVc.hidesBottomBarWhenPushed = true
```

`someVc` at the beginning will appear normal `[BottomBar hidden]` until you try to **_scroll_**, then the **BottomBar**'s space will appear [with White space only, no tabs]. 

Note: I am using CollectionView and the Root View Controller is a TabBarViewController. I was trying to make all the View Controllers accessed from the TabBarViewController appear without the bottom tab bar, this was working fine until I started hiding the navigationBar on scroll. 

Any idea how can I work around this?

**Comment by hcrub** [comment]
+1

In my case, I have a Tab Bar mine doesn't necessarily re-appear, but theres a blank gap _(of the same size of the Tab Bar)_ at the bottom of the screen the scrolling initially begins. My View Controllers override `hidesBottomBarWhenPushed` to determine if the Tab Bar should show/hide. From what I can see, the setup doesn't seem to acknowledge the `hidesBottomBarWhenPushed` when determining the `tabBarOffset` calculated property defined [here](https://github.com/andreamazz/AMScrollingNavbar/blob/master/Source/ScrollingNavbar%2BSizes.swift#L25).

As a quick fix, I modified the following in `ScrollingNavbar+Sizes` to ignore the Tab Bar height if the foremost View Controller's`hidesBottomBarWhenPushed` property evaluates `true`. 
```swift
var tabBarOffset: CGFloat {
    // Only account for the tab bar if a tab bar controller is present and the bar is not translucent
    if let tabBarController = tabBarController {
        // If the foremost view controller hides the tab bar, ignore the height and prevent additional offset.
        if let topViewController = topViewController, topViewController.hidesBottomBarWhenPushed {
            return 0
        }
        return tabBarController.tabBar.isTranslucent ? 0 : tabBarController.tabBar.frame.height
    }
    return 0
}
```
Note that this is not an open-implementation and I was forced to clone for now. I'll attempt a PR in the near future.
