### ISSUE TITLE
Wrong current release and version number

### ISSUE THREAD

**Issue by anfriis** [andreamazz/AMScrollingNavbar#247]
Carthage has problems detecting the newest release, since the newest tag is not marked as the current release. 
And when you look at the targets Version in the Xcode project it is set to `2.0.10`... 
Could you please update it also when you update the pod spec, so it will work for Carthage users? :)

**Comment by andreamazz** [comment]
Hi @anfriis 
I've pushed the updated project and embedded the compiled framework to the current tag, let me know if that fixes the issue or if I have to tag a new release

**Comment by anfriis** [comment]
Yes it worked, thank you!
