### ISSUE TITLE
Wrong layout when blue staus bar is visible

### ISSUE THREAD

**Issue by NachoSoto** [andreamazz/AMScrollingNavbar#248]
![img_3643](https://cloud.githubusercontent.com/assets/685609/25831368/59099780-3418-11e7-9c4b-714252572988.PNG)
![img_3644](https://cloud.githubusercontent.com/assets/685609/25831369/591fd23e-3418-11e7-9707-11e0880246c8.PNG)
Both when the bar is collapsed or expanded.

This can be reproduced on the sim as well.

**Comment by andreamazz** [comment]
Hi @NachoSoto 
I've pushed a fix in master. I'm not terrible happy with it, since I had to clamp the status bar height to 20 points, but it seems to be working.  
Let me know if you find anything else.

Cheers

**Comment by andreamazz** [comment]
Closing this for now, let me know if the issue persist.
