### ISSUE TITLE
Mark methods from UIGestureRecognizer as open

### ISSUE THREAD

**Issue by m1entus** [andreamazz/AMScrollingNavbar#249]
I would like to change in my subclass method `  public func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldRecognizeSimultaneouslyWith otherGestureRecognizer: UIGestureRecognizer) -> Bool {
    return true
  }` and i can't because it is defined as public not as `open`, please change it, thanks!

**Comment by andreamazz** [comment]
Fixed in version `3.3.3`
