### ISSUE TITLE
Why when I click on the status bar, become like this?I test the demo of 1.x version.

### ISSUE THREAD

**Issue by misscxuan** [andreamazz/AMScrollingNavbar#250]
![simulator screen shot 2017 5 15 3 03 38](https://cloud.githubusercontent.com/assets/17959278/26046065/c20c2402-397f-11e7-88cb-6b27ddfe357f.png)

**Comment by andreamazz** [comment]
Hey @misscxuan 
I would advise against using version 1.x at this moment. Is there any way for you to upgrade to version 2?

**Comment by misscxuan** [comment]
Thank you for your reply! I use the Object-C to write my project, so  I used the version 1.x before.I have used the following method to solve this problem, and it works.
![image](https://cloud.githubusercontent.com/assets/17959278/26063645/2c08e35e-39c1-11e7-9a02-599b1c38671f.png)

**Comment by misscxuan** [comment]
Now I will try to solve this problem with version 3, thanks again.

**Comment by andreamazz** [comment]
👍
