### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by songhailiang** [andreamazz/AMScrollingNavbar#253]
Hi, 
When i check the code, i think this might be wrong in ```checkForPartialScroll``` method, see the code below:
```
    let frame = navigationBar.frame
    var duration = TimeInterval(0)
    var delta = CGFloat(0.0)
    let distance = delta / (frame.size.height / 2)
```
```delta``` is 0, so ```distance``` is also 0, is this right?

Thanks.

**Comment by andreamazz** [comment]
@songhailiang 
Good point. Let me check.

**Comment by andreamazz** [comment]
Thank you @songhailiang 
I've reinstated the code that was missing in the latest commit
