### ISSUE TITLE
Not a issue but a request:How to make the navBar and tabBar scroll at the same time ?

### ISSUE THREAD

**Issue by dongdong3344** [andreamazz/AMScrollingNavbar#259]
If there is a controller which has a navigation bar and a Tabbar.
How to make the nav-bar scroll up and the tabBar scroll down gradually and hide them at the same time when user scroll up the tableView?
And when scroll down tableView，the contrary scrolling direction for nav-bar and tabBar.  
Can you add this request function?

**Comment by andreamazz** [comment]
Hey @dongdong3344 
This was added today in #258 
Checkout the latest master version, I'll push a new release soon.

**Comment by dongdong3344** [comment]
@andreamazz  so cool. Thanks a  lot.
