### ISSUE TITLE
Black bar under navigation bar when adding view on scroll

### ISSUE THREAD

**Issue by pareekkhushboo77** [andreamazz/AMScrollingNavbar#260]
when i add a subview , when the navigation bar is scrolled up, it adds a black background under navigation bar, i dont know why it happens like that, please help if anyone is aware about the issue.
![simulator screen shot 12-jul-2017 12 10 27 pm](https://user-images.githubusercontent.com/16894064/28105036-7ced2656-66fb-11e7-8fc8-5e9da7e37430.png)

**Comment by andreamazz** [comment]
Hey @pareekkhushboo77 
can you share the detail steps to reproduce this issue?

**Comment by pareekkhushboo77** [comment]
@andreamazz , i solved this issue, it was my autolayout issue, the origin of my table view was below navigation bar, i just made the origin over navigation bar i.e. top of the screen and it solved my problem.
Thanks for your instant response. :)

**Comment by ArthurBodrov** [comment]
Check another solution here: https://github.com/andreamazz/AMScrollingNavbar/issues/210#issuecomment-1491277964
