### ISSUE TITLE
NavigationController title off on iPhone X

### ISSUE THREAD

**Issue by cjrieck** [andreamazz/AMScrollingNavbar#266]
Hi there! Thank you for the awesome library! I was running my app using the Xcode 9 GM and iPhone X simulator when I noticed the `title` was a bit close to the notch in the sim:

<img width="545" alt="screen shot 2017-09-15 at 10 35 21 am" src="https://user-images.githubusercontent.com/1785533/30487476-9ce2024a-9a01-11e7-8e47-6be3477c779d.png">

This only happens after the navbar collapses and expands. It's starts out ok.

It could be an issue is in the `statusBarHeight` here:

```swift
var statusBarHeight: CGFloat {
    return CGFloat.minimum(20, UIApplication.shared.statusBarFrame.size.height)
}
```

~~Not sure how big the status bar height is now, but~~ The status bar height is `44` for iPhone X, so it seems like the `20` needs to be updated for iOS 11 and iPhone X. I confirmed that returning only the `UIApplication.shared.statusBarFrame.size.height` fixes the issue. Any help would be greatly appreciated!

**Comment by andreamazz** [comment]
> The status bar height is 44 for iPhone X, so it seems like the 20 needs to be updated for iOS 11 and iPhone X. I confirmed that returning only the UIApplication.shared.statusBarFrame.size.height fixes the issue. Any help would be greatly appreciated!

Great to hear that. I'm trying to remember why that `minimum(20, ` is in place, but for now, nothing comes to mind 😬

**Comment by cjrieck** [comment]
No worries! Thanks for the help and speedy response!

**Comment by andreamazz** [comment]
👍 
Release `4.0.1` with the fix.

**Comment by landsv** [comment]
What about this fix for version 3.x ?

**Comment by andreamazz** [comment]
Sure, feel free to open a pull request.
