### ISSUE TITLE
Build Error for NSAttributedStringKey

### ISSUE THREAD

**Issue by robmontesinos** [andreamazz/AMScrollingNavbar#267]
I am in the middle of submitting to the App Store, and I updated cocoa pods prior to archiving. On build I get the following error: **Use of unresolved identifier 'NSAttributedStringKey'** - there are three instances of the error below.

My deployment target is iOS 10.3

The code triggering the errors is in ScrollingNavigationController line 432:

```
    if let titleColor = navigationBar.titleTextAttributes?[NSAttributedStringKey.foregroundColor] as? UIColor {
      navigationBar.titleTextAttributes?[NSAttributedStringKey.foregroundColor] = titleColor.withAlphaComponent(alpha)
    } else {
      navigationBar.titleTextAttributes?[NSAttributedStringKey.foregroundColor] = UIColor.black.withAlphaComponent(alpha)
    }
```

I understand that NSAttributedStringKey is an iOS 11 API.

Any suggestions as to how I should proceed in handling the updateNavbarAlpha() function?

Thank you so much.

**Comment by andreamazz** [comment]
https://github.com/andreamazz/AMScrollingNavbar/blob/master/README.md#versioning-notes

Use version 3.x

**Comment by robmontesinos** [comment]
@andreamazz you are the bomb!! 8 minute response that worked - wow!! Thank you for all of your work and all the best!!

**Comment by Katafalkas** [comment]
Hey. I have the same issues. I do not want to downgrade to 3.x as I need a iPhone X compatibility as it is in 4.0.1. My code is in Swift 4.0 and it seems like this particular Pod is compiled in Swift3.

What am I missing?

**Comment by andreamazz** [comment]
Version 4.x is compiled with Swift 4. Make sure that your pod project is using the correct version of swift.
you might need something like this in your post installs critps:
```

swift4pods = ['AMScrollingNavbar']

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if swift4pods.include? target.name
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.0'
      end
    end
  end
end
```

But this is odd, if you run `pod install` your project should default to 4.

**Comment by bgonzales** [comment]
Hi @andreamazz ! I am using the version 4.2.1 in a private pod like this:

```
s.pod_target_xcconfig   = { 'SWIFT_VERSION' => '4.0' }
...
s.dependency 'AMScrollingNavbar', '4.2.1'
```

But when I try to `pod lib lint` the project I am still getting the errors: 

``` 
AMScrollingNavbar/Source/ScrollingNavigationController.swift:462:60: error: type 'NSAttributedStringKey' (aka 'NSString') has no member 'foregroundColor'
AMScrollingNavbar/Source/ScrollingNavigationController.swift:465:42: error: type 'NSAttributedStringKey' (aka 'NSString') has no member 'foregroundColor'
```

Do you have any ideas on this ? Thanks

**Comment by andreamazz** [comment]
Looks like it's compiling it against Swift 3. Can you check the Swift version in target AMScrollingNAvbar inside your Pods project?

**Comment by bgonzales** [comment]
It's Swift 4.0

**Comment by andreamazz** [comment]
That's really weird, that error message is typical when you compile it with Swift 3 🤔 
Also, those lines are wrong in the current version of the file:
https://github.com/andreamazz/AMScrollingNavbar/blob/master/Source/ScrollingNavigationController.swift#L462

462 points to an empty line
