### ISSUE TITLE
A View between Navigation Controller and CollectionView not working with constraints

### ISSUE THREAD

**Issue by omerfarukyilmaz** [andreamazz/AMScrollingNavbar#268]
Creating a Navigation Controller, Tab Bar, a UIView, and a Collection View programmatically I get this issue:

_I may be doing something wrong myself. I am not very experienced creating views programmatically, so bare with me._

When the collectionview's constraints are set to topLayoutGuide.bottomAnchor, it works amazing. But when does there is any UIView in between, it does not work well.

Screenshot:

![simulator screen shot - iphone 8 - 2017-09-18 at 22 09 22](https://user-images.githubusercontent.com/5538485/30546502-59bae110-9cbf-11e7-86a9-e4651970c59c.png)

Adding to the followers: [] also does not work.

Project Link replicating the issue:
https://github.com/omerfarukyilmaz/ExampleAMScrollingNavbar

Sorry if the title is not very descriptive. I tried explaining detailed in the post.

Btw, love the library and I'm very grateful for it. 👍

**Comment by toseefkhilji** [comment]
+1

**Comment by andreamazz** [comment]
Hi @omerfarukyilmaz 
Sorry it took me so long to respond.
The library is meant to follow and adapt the view for a scrollview, if you want to add a toolbar up top you should use the followers params, passing in your view. Alternatively you can use that view as the collectionview header.

**Comment by omerfarukyilmaz** [comment]
Collectionview header would actually do the trick! Thank you.

And no worries, the library is great so thank you for all your work 👍.

**Comment by yogesh-nykaa** [comment]
@omerfarukyilmaz  Well changing 
`navigationController.followScrollView(collectionView)`

To

`navigationController.followScrollView(collectionView, delay: 0.0, followers: [fakeView, collectionView])`

will resolve the issue. I have tried the same and posting the answer.

@andreamazz Is there any way, we can scroll the green view to top, means hiding same as navigation bar along with navigation bar?
