### ISSUE TITLE
NavigationBar does not expand when scrollview has bottom content inset

### ISSUE THREAD

**Issue by evgenykarev** [andreamazz/AMScrollingNavbar#271]
If I set bottom content inset in tableView such as

`tableView.contentInset.bottom = 200`

swipe gesture does not expand navigationBar, when content in the bottom of scrollView, while contentOffset less than tableView bottom contentInset.

Thanks!

**Comment by andreamazz** [comment]
Fixed thanks to @bobek-balinek
