### ISSUE TITLE
In-call status bar causes the navigation bar to expand too far

### ISSUE THREAD

**Issue by bobek-balinek** [andreamazz/AMScrollingNavbar#273]
Hi there, I'm struggling to identify what causes this weird bug. This is running the Demo project on an iOS 11 simulator but it also happens on my own project. I'm not too familiar with the internals of this module so I was wondering if you could point me to the right section so we could fix this.

![a](https://user-images.githubusercontent.com/913452/31464148-7a881578-aec8-11e7-970a-14006b0badfb.gif)

**Comment by Alexookah** [comment]
@andreamazz why did you reopen this?

**Comment by andreamazz** [comment]
Dunno, but it seems to be fine. Closing again
