### ISSUE TITLE
Presenting a 'modal' view controller causes the navigation bar to be shown

### ISSUE THREAD

**Issue by bobek-balinek** [andreamazz/AMScrollingNavbar#275]
Whenever I use the `present` or `performSegue` methods to present a view controller on top of the scrolling navigation controller it appears to show the navigation bar whenever you dismiss it but with all the subviews are hidden. I've inspected the view hierarchy and surprisingly the alpha values are set to 1. Any ideas what might have caused this?

![d](https://user-images.githubusercontent.com/913452/31544810-8cd57eda-b014-11e7-9f3d-cb8b1bd0873a.gif)

**Comment by alejouribesanchez** [comment]
One solution is to call stopFollow method before use present or performSegue, that happened to you because when the navigation bar is collapsed all subviews in the navigation bar are hidden, other way is calling showNavBar method before use present or performSegue.
