### ISSUE TITLE
Can install AmscrollingNavbar on Swift 4

### ISSUE THREAD

**Issue by atistank** [andreamazz/AMScrollingNavbar#281]
hi my project currently coding in Swift 4, when i try install on cocoapods it still install  AmscrollingNavbar ver 3.0.2 and I've got an error: no such module AMScrollingNavbar ?

how i can fix it ? thanks

**Comment by alejouribesanchez** [comment]
@atistank Show me your pod file maybe I can help you

**Comment by atistank** [comment]
`# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Project1_Duy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Project1_Duy
pod 'AMScrollingNavbar'

  target 'Project1_DuyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Project1_DuyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end`

thanks in advance

**Comment by alejouribesanchez** [comment]
Change this line pod 'AMScrollingNavbar' to pod 'AMScrollingNavbar', '~> 4.0.4'
in your terminal in the folder of your project run: pod repo update
then run: pod install

Also in the pods target select AMScrollingNavBar and then change Swift language to 4.0
![screen shot 2017-10-22 at 2 04 51 am](https://user-images.githubusercontent.com/3950665/31859156-8435fc40-b6cd-11e7-9b0d-39359782de4b.png)
![screen shot 2017-10-22 at 2 04 15 am](https://user-images.githubusercontent.com/3950665/31859165-87f1163a-b6cd-11e7-8062-9f55d7930169.png)

**Comment by atistank** [comment]
it not working for me :(

> 
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `AMScrollingNavbar (~> 4.0.4)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `AMScrollingNavbar (~> 4.0.4)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
>

**Comment by alejouribesanchez** [comment]
run in your terminal: $ [sudo] gem install cocoapods
then run: $ pod repo update
then again: $ pod install

**Comment by alejouribesanchez** [comment]
I tried in my computer and it's working good the problem is not AMScrollingNavbar the problem is your pod file and cocoa pods command.

**Comment by alejouribesanchez** [comment]
@atistank  if your project is in objective c you can test with this: https://github.com/alejouribesanchez/ScrollHideNavigationController

**Comment by andreamazz** [comment]
@atistank 
run 
```
rm -rf ~/.cocoapods/repos/master
pod setup
```

To be sure also delete your `Podfile.lock` then run `pod install` again.

**Comment by atistank** [comment]
thanks for you support. it worked :D
