### ISSUE TITLE
Navigation bar large titles support

### ISSUE THREAD

**Issue by Mazorati** [andreamazz/AMScrollingNavbar#284]
Hello!
Large titles and section headers #283  issue below:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3396425/31876404-3044e880-b7db-11e7-9209-f3683c3c8e1e.gif)

**Comment by Mazorati** [comment]
Solved,
in ScrollingNavigationController.swift
at line 446
i remove className == "UINavigationBarContentView" ||
and add className == "UINavigationBarLargeTitleView"
Also i add UINavigationBar.appearance().isTranslucent = false

**Comment by andreamazz** [comment]
Nice catch @Mazorati 
I've added the largetitleview to the check in `master`

**Comment by Mazorati** [comment]
@andreamazz it is not that easy. When you use Large titles - you have to **remove** "UINavigationBarContentView" and add className == "UINavigationBarLargeTitleView". Because default title not hiding!

**Comment by andreamazz** [comment]
Good point. https://github.com/andreamazz/AMScrollingNavbar/commit/dfb6baf7cb7a3901cef4a3a90d5d23735f5e7786 should take care of that. I've also added a sample.
