### ISSUE TITLE
followers offset broken

### ISSUE THREAD

**Issue by godexsoft** [andreamazz/AMScrollingNavbar#286]
I have the following setting:
- navigation controller with collection view and a blur view that is behind the (otherwise transparent) navbar
- this blur view is added to the followers array
- a child controller accessible thru "show" segue on tap of a cell in the collection view

What happens:
- if i tap the cell to show the child controller AND the navbar is fully visible at that time, ALL IS FINE
- if i tap the cell to show the child controller AND the navbar is hidden (scrolled out behind top of screen) when i close that child controller to go back to my original collection view, the navbar is automatically shown but the follower blur view is in the same hidden position as i left it. from now on the follower is always offset by that navbar height and even tho it's being shown/hidden correctly with the navbar but it's in a wrong position at all times.
- repeating the exercise further offsets the blur view rendering it completely invisible (out of bounds of the screen)

Thanks

**Comment by godexsoft** [comment]
Bump

**Comment by andreamazz** [comment]
Not sure how I can reproduce this... please provide a sample of code to test this out.

**Comment by godexsoft** [comment]
@andreamazz i created a small demo project that shows the bug i'm experiencing as well as a new bug discovered in the process (maybe i did something wrong for it to happen tho because it seems really odd).
All instructions to reproduce the bugs are built into the app's UI as labels and buttons.
Please download the demo app from here: https://drive.google.com/open?id=1Du3D3sPmNTCwc50iiIGYlz40bYzG-PQo

Thank you

**Comment by andreamazz** [comment]
@godexsoft 
thank you for the sample project.
Those behaviours are expected, the solution is described in the readme: https://github.com/andreamazz/AMScrollingNavbar#handling-navigation

**Comment by godexsoft** [comment]
@andreamazz amazing and easy fix. Thanks! I can only suggest you add the same info to the "Followers" block in the doc because it's too easy to overlook right now. Thanks for your time
