### ISSUE TITLE
error in swift 3.2

### ISSUE THREAD

**Issue by mohamamdkalim** [andreamazz/AMScrollingNavbar#287]
Hello,

can you let me know what to update i have facing error in my app... screenshot is attached

https://www.dropbox.com/s/ojfb6o4q34mkniz/eror.png

**Comment by andreamazz** [comment]
If you are using Xcode 9 just compile the pod with Swift 4, otherwise use version 3.x

**Comment by mohamamdkalim** [comment]
i am using xcode 9.1 and swift 3.2 still facing same error in the pod file i write:

  pod 'AMScrollingNavbar'

can you please help me

**Comment by andreamazz** [comment]
You can add this at the bottom of your Podfile:

```
swift4pods = ['AMScrollingNavbar']

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if swift4pods.include? target.name
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.0'
      end
    end
  end
end
```

**Comment by mohamamdkalim** [comment]
thanks solved
