### ISSUE TITLE
iPhone X display issue for TabBar

### ISSUE THREAD

**Issue by aloveric** [andreamazz/AMScrollingNavbar#288]
![simulator screen shot - iphone x - 2017-11-16 at 15 54 06](https://user-images.githubusercontent.com/8198881/32879841-317a712c-ca71-11e7-8e7e-66d8e3755813.png)

![simulator screen shot - iphone x - 2017-11-16 at 15 53 54](https://user-images.githubusercontent.com/8198881/32879845-3333ea52-ca71-11e7-8db9-28e8ce6bb139.png)

**Comment by andreamazz** [comment]
This should be fixed now. Let me know if you still encounter this issue.
