### ISSUE TITLE
iOS 11 + Large title + searchBar + Refresh control

### ISSUE THREAD

**Issue by AYastrebov** [andreamazz/AMScrollingNavbar#294]
Hello!

I've setup a sample project with tall navigationBar + searchBar + RefreshControl. Everything seems to work fine, except navbar scrolling.
I couldn't manage get it to work with navBar hiding

Here is a sample project, I would be glad if some one could point me a right way

https://www.dropbox.com/s/6cfglbvpkj0p3dt/NavBarTest.zip?dl=0

**Comment by andreamazz** [comment]
@AYastrebov 
glad you were able to solve it. Please consider restoring the issue text and provide the solution. That could be helpful to other users in the future.
