### ISSUE TITLE
IPhone X without status bar BUG

### ISSUE THREAD

**Issue by mateo666** [andreamazz/AMScrollingNavbar#295]
The navigation bar does not respond correctly when there is no status bar shown.
When the status bar is shown, it is ok.
Else it is pushed up where the status bar should be and the following views are then not rendered properly.

**Comment by NightWarrior** [comment]
Something similar is happening to me as well, need a quick work around... I'm using a tableview and when reloadData is called then the navigationbar goes up in IphoneX like there is no statusbar and leaves some space below it... till where the tableview content top inset ends and content begins...

**Comment by NightWarrior** [comment]
Never mind, right after posting the above comment, i tried the solution in https://github.com/andreamazz/AMScrollingNavbar/issues/266
I had to open the pod obtained files, unlock and make the change... It appears as for Swift 3.2, the pod install gave me files which arent updated with the fix.

mateo666 maybe your issue is the same as well. 

Also if anyone knows, would my solution do any potential harm? I dont plan on messing with the statusbar myself in anyway.

**Comment by andreamazz** [comment]
The branch `swift3` should already have that fix. You can use that in your Podfile:
```
pod 'AMPopTip', branch: 'swift3'
```

**Comment by mateo666** [comment]
So which version should i use for swift 4 ?
i had 4.1.0 but i see its different than 4.0.1 regarding the statusBarHeight.

**Comment by andreamazz** [comment]
Use the latest version for swift 4

**Comment by mateo666** [comment]
which is ?

**Comment by andreamazz** [comment]
4.1.0

**Comment by mateo666** [comment]
it is not working with 4.1.0
i have to include the status bar. if i mark it as not visible in the info.plist then when the navbar is shown it is not correctly positioned and some part of my screen is not shown also.
But if the status bar is visible, everything works great.

**Comment by andreamazz** [comment]
Got it, let me see if I can fix this quickly.

**Comment by andreamazz** [comment]
Gotta love that notch...  
I'm not sure what should be the best course of action here. I can force the library to consider a 'ghost' status bar as big as the safe area, the result is something like this:

<img width="478" alt="screen shot 2017-12-19 at 18 02 59" src="https://user-images.githubusercontent.com/570797/34169254-13f89f6c-e4e7-11e7-935d-b35a5d7ea6fa.png">

Which I guess is fine, but from an implementation perspective is nightmare fuel.

Thoughts?

**Comment by andreamazz** [comment]
@mateo666 
can you test commit 9e4bfe3?

**Comment by mateo666** [comment]
looks good ! thanks
