### ISSUE TITLE
Leading and trailing constraints changes when scrolling

### ISSUE THREAD

**Issue by Ariavm95** [andreamazz/AMScrollingNavbar#298]
Hi,
I have a UIScrollView under a navigation bar, and there is a text view in the scroll view. When I use AMScrollingNavbar, it suddenly changes Leading and trailing constraints when scrolling. Has this happened to somebody?

**Comment by andreamazz** [comment]
Hi @Ariavm95 
Is your setup different from the one in the sample project?

**Comment by Ariavm95** [comment]
I found out the issue was not caused by your code. I created a tab bar right under nav bar and another on the bottom of screen. The constraints change when I go back to specific tab page from other tab pages. I fixed it with using layoutIfNeeded method in viewWillAppear.
