### ISSUE TITLE
Tilting device causes a problem

### ISSUE THREAD

**Issue by Ariavm95** [andreamazz/AMScrollingNavbar#299]
Hi,
I'm using AMScrollingNavbar, and it works perfectly on a simulator, but it has a problem when testing it on a real device. When I tilt the device, it seems it triggers something and navigation bar becomes visible again!!!!!
Is there anyway to turn this behavior off?

**Comment by andreamazz** [comment]
Nope, it's intended behavior to work around UIKit (the navbar is shown by the OS)

**Comment by Alexookah** [comment]
There is a difference between tilting the device Face Up/Down (portrait) with left / right (landscape).

i faced the same issue and could not find why the navigation bar was showing randomly...up

After hours of debugging and trying to find a resolution. I found out that the navigationbar was showing also on Face Up & Face Down, which in my opinion is totally wrong.

 so I simply commented the following line of code to resolve.

 func didRotate(_ notification: Notification) {
 //showNavbar()
 }

**Comment by Ariavm95** [comment]
@Alexookah By tilting, I didn't mean rotating in xy plane. I mean shaking in yz plane. https://hacks.mozilla.org/files/2015/04/cyber-orb-flame-orientation.png
![cyber-orb-flame-orientation](https://user-images.githubusercontent.com/13060287/37004129-52093e5a-2084-11e8-9587-4ed1b5088038.png)

**Comment by Alexookah** [comment]
i am saying the exact same thing. Face Up / Down is tilting in yz plane. In simulator you can find it in hardware orientation face up / Face Down. With hidden navigation Bar if you select face Down or up you can see the navigation bar shows up.

**Comment by Alexookah** [comment]
NotificationCenter.default.addObserver(self, selector: #selector(ScrollingNavigationController.didRotate(_:)), name: NSNotification.Name.UIDeviceOrientationDidChange, object: nil)

this observer is triggered also on yz plane

**Comment by andreamazz** [comment]
Good point, fixed in c382e61
Thank you for the feedback 👍
