### ISSUE TITLE
Tab bar is not fully hidden while scrolling on iPhone X

### ISSUE THREAD

**Issue by mohammedsafwat** [andreamazz/AMScrollingNavbar#304]
Hello,

I have faced an issue on iPhone X related to the position of the tab bar. It's not totally hidden while scrolling. I have attached a screenshot:

<img width="431" alt="screen shot 2018-03-07 at 10 34 54 pm" src="https://user-images.githubusercontent.com/241657/37120057-8d047a5c-2259-11e8-9613-63d4612c281f.png">

I was able to fix this by changing `tabBar.frame.origin.y += delta * 1.5` to `tabBar.frame.origin.y += delta * 2.0` inside `updateFollowers()` method. I'm not sure if this is the correct way to fix this issue? Your advice is appreciated.

Thanks!

**Comment by andreamazz** [comment]
The correct ratio is something like this
```
      tabBar.frame.origin.y += delta * (tabBar.frame.height / navigationBar.frame.height)
```
I'll fix it. Thanks for pointing this out.

**Comment by andreamazz** [comment]
Fixed in `4.2.3`

**Comment by mohammedsafwat** [comment]
I tested again after using the new fix `tabBar.frame.origin.y += delta * (tabBar.frame.height / navigationBar.frame.height)`, at first, things seem to be fine but after scrolling for a while I started to see some wrong positions for the tab bar. I have attached some screenshots for your reference. Things were fine after I reverted the fix and used `tabBar.frame.origin.y += delta * 2`.

![img_7597](https://user-images.githubusercontent.com/241657/37146047-f1004536-22c2-11e8-96d4-4aae32c1f803.PNG)

![img_7598](https://user-images.githubusercontent.com/241657/37146054-f5793de8-22c2-11e8-8cdd-286ee510d61e.PNG)

Thanks a lot for your help!

**Comment by andreamazz** [comment]
Just by scrolling? I'm trying to reproduce the issue, but with no luck. Any idea on how to reproduce this? 
Your solution (using `2`) is fine for now, but it might break in future versions.

**Comment by mohammedsafwat** [comment]
Hi Andrea,

Apologies for my late response. I wanted to properly test the cases again. Apparently, it was something from my side. There's a famous iPhone X related issue when the tab bar jumps on pushing a new ViewController. My fix for this tab bar issue was causing this weird behavior. After removing that, the tab bar now is showing and hiding properly using `(tabBar.frame.height / navigationBar.frame.height)`. This approach is, of course, better than hardcoding the multiplication of `2`. 

Thanks a lot for your help!
