### ISSUE TITLE
Status bar click Does not fully scroll to Top

### ISSUE THREAD

**Issue by Alexookah** [andreamazz/AMScrollingNavbar#305]
I noticed that clicking the status Bar, does not fully scroll to top.

check the following video
https://streamable.com/pzwrg

the reproduce config code is the same as my previous bug report https://github.com/andreamazz/AMScrollingNavbar/issues/302:

https://github.com/Alexookah/AMScrollingNavbar

**Comment by andreamazz** [comment]
Yeah, it looks like the insets are updated after the full scroll, so a 44px content offset remains. 
Not sure how to fix this at the moment, any help is more than welcome.

**Comment by fullc0de** [comment]
It only happens on iOS 11.

**Comment by fullc0de** [comment]
@Alexookah 
I haven't found what it causes, but found a workaround by modify my codes like the following.

    func scrollViewShouldScrollToTop(_ scrollView: UIScrollView) -> Bool {
        if let navigationController = navigationController as? ScrollingNavigationController {
            navigationController.showNavbar(animated: true)
            collectionView.setContentOffset(.zero, animated: true)
            return false
        }
        return true
    }

Unlike `scrollViewShouldScrollToTop` delegate method in `ScrollingNavigationViewController`, `contentOffset` in collectionView is handled directly and the method returns `false` to block scrolling by the system.

**Comment by andreamazz** [comment]
Thank you @fullc0de for the detective work, it looks like it was introduced in 4.2.1 with this commit:
https://github.com/andreamazz/AMScrollingNavbar/commit/afcdf843b5942b86978293ca2463313b384e4ab4

The code breaking the scroll to top is this one:
https://github.com/andreamazz/AMScrollingNavbar/blob/master/Source/ScrollingNavigationController.swift#L390-L395
Commenting out the call to that method works, but it was set there to solve issue #219.  
Any idea is welcome 😬

**Comment by CaliCastle** [comment]
@Alexookah 
I think it's because of the new `safeAreaInsets` that was introduced in iOS 11 causing this particular issue and I found a workaround that works pretty well:

```swift
override func scrollViewShouldScrollToTop(_ scrollView: UIScrollView) -> Bool {
        if let navigationController = navigationController as? ScrollingNavigationController {
            navigationController.showNavbar(animated: true)
            
            if #available(iOS 11.0, *) {
                DispatchQueue.main.async {
                    if scrollView.contentOffset != .zero {
                        scrollView.setContentOffset(CGPoint(x: 0, y: -scrollView.safeAreaInsets.top), animated: true)
                    }
                }
            }
        }
        
        return true
    }
```

Hope that helps!

**Comment by StefaniOSApps** [comment]
this bug was fixed in my pull request #338

look to my Demo Project
 https://github.com/StefaniOSApps/Example

**CLOSED**

**Comment by StefaniOSApps** [comment]
it looks like the BUG is not complete fixed yet.

I found this problem when :

1. Normal UiViewController (OK)
2. Present >> PageSheet (OK)
3. present >> FormSheet (OK)
4. Push >> UiViewController (FAIL)

it scrolls up, but the bar is not showing.

**pending**

**Comment by StefaniOSApps** [comment]
Furthermore, it flutters. The reason is that with the automatic scroll up, the status bar seems to want to hide again. this creates a contradiction.

**Comment by StefaniOSApps** [comment]
ok, the first issue is not a problem of the framework, but the second is real (flutters / blinked);
