### ISSUE TITLE
navbar height

### ISSUE THREAD

**Issue by tdotyep** [andreamazz/AMScrollingNavbar#306]
I have a UIButton in the center of my navbar and I am unable to set the height of the navbar to pad the bottom of the UIbutton (navbar ends right at the bottom of the button).  

I have tried to use navigationController.navigationBar.frame.size.height, but it doesn't do anything.  

I have also tried to set contentEdgeInsets.bottom but nothing as well.  Any help is appreciated. Thanks!

**Comment by andreamazz** [comment]
Not sure how this relates to this library though. The height of the navbar is enforced by iOS itself.

**Comment by tdotyep** [comment]
it's related because I'm using this library and having a problem extending the height of the navbar so I came here looking for help.

**Comment by andreamazz** [comment]
Can you extend the height without this lib installed?
