### ISSUE TITLE
Navigation controllers set as `ScrollingNavigationController` in storyboard are instantiated as `UINavigationController`

### ISSUE THREAD

**Issue by heruvilius** [andreamazz/AMScrollingNavbar#308]
Hello. I have a little problem with the framework.

I have a `UITabBarController` that has 4 tabs. These tabs are navigation controllers, and I'd like their navigation bars to follow some scroll views. The issue is that 

    self.navigationController as? ScrollingNavigationController always returns nil

I've set all the 4 navigation controllers inside my app to `ScrollingNavigationController` through storyboard, yet all of them are still being instantiated as `UINavigationController`.

Could you please suggest an idea where I might be wrong? Thanks.

**Comment by andreamazz** [comment]
Hi. Make sure that the field below the class name, module, is set to 'AMScrollingNavbar'. 
I had the same issue while building a demo last week, I'm guessing it's an Xcode issue.

**Comment by heruvilius** [comment]
@andreamazz That fixed the issue. Thanks.
