### ISSUE TITLE
Change direction of a follower?

### ISSUE THREAD

**Issue by L4grange** [andreamazz/AMScrollingNavbar#312]
Hello! First of all I would like to thank you for this library, I've used it in almost all my projects!

I'm trying to create a custom TabBar instead of the normal TabBar, and I need to make it follow my scrollView. However, now with the library, my custom tabBar (it's actually a UICollectionView at the bottom of the creen that scrolls horizontally) moves upwads instead of downwards.

Is there a way to pass into the `navigationController.followScrollView` method the direction in which the custom view must follow the scrollView?

**Comment by andreamazz** [comment]
Hey @L4grange 
check out the latest commit in master, I've made some changes to the `followers` param. Now it's no longer an array of `UIView`s, but a custom object, `NavigationBarFollower`. This wrapper holds the view and the scroll direction. If you check the collection view sample, you'll see how to implement it.

```swift
navigationController.followScrollView(collectionView, delay: 50.0, followers: [NavigationBarFollower(view: customFooter, direction: .scrollDown)])
```

**Comment by L4grange** [comment]
Just what I needed! Thank you so much :)

**Comment by L4grange** [comment]
Just tested on my app and there seems to be a problem. My custom view has the exact same frame as a TabBar (but it's a UICollectionView) and when it slides down, its does not completely hide itself. There is about 5 pixels left visible of the top of the view. I can provide you with a screenshot if needed. Any ideas on how to fix this?

**Comment by andreamazz** [comment]
@L4grange 
should be fixed in master, let me know if that works

**Comment by L4grange** [comment]
Works perfectly now, thank you so much!
