### ISSUE TITLE
Tabbar follower doesn't return to the original position when the app goes to background

### ISSUE THREAD

**Issue by lawicko** [andreamazz/AMScrollingNavbar#313]
Steps to reproduce:

1. In the application with the UITabBarController as the root view controller, have AMScrollingNavbar instance in one of the tabs.
1. Make the tab bar a follower of the scrolling navbar.
1. Scroll the scroll view so that the navigation bar and the tab bar disappears.
1. Make the app go to background by tapping on the home button or whatever.
1. Come back to the app.

Expected: As in previous versions, I'd expect the tab bar becomes visible.

Actual: The tab bar stays hidden, so now there is no way to actually get the tab bar back.

Note: This bug was introduced in c382e61bf04b111a420b29f6066e006927ee2abd

**Comment by andreamazz** [comment]
Well, I'll cross it off as UIKit being UIKit. 
Apparently a rotation is triggered when going back to foreground, and that `showNavbar` was required. This should be ok now, let me now.
