### ISSUE TITLE
Example with Tableview + UIToolBar breaks if toolbar height is not 44

### ISSUE THREAD

**Issue by hammadzz** [andreamazz/AMScrollingNavbar#317]
Changing the UIToolBar height to 34 results in this issue:

![simulator screen shot - iphone x - 2018-06-04 at 19 25 11](https://user-images.githubusercontent.com/6963295/40946711-045a6e04-682d-11e8-816c-0ca1b333282a.png)

**Comment by xieweizhi** [comment]
I found the same issue here.

**Comment by andreamazz** [comment]
Fixed in master. 
I've made some major changes on how the state is handled, please test it out.
