### ISSUE TITLE
Custom Footer issue on iPhone X

### ISSUE THREAD

**Issue by tungdx** [andreamazz/AMScrollingNavbar#318]
Thanks for creating a great library!

I have run the sample on iPhone X and found that it's error while scrolling with custom footer (I've also tried with on bottom and got the same problem).
How can I fix that? Thanks!
![image](https://user-images.githubusercontent.com/1876051/42288206-fba0db6c-7fe3-11e8-8a5b-3128f8428043.png)

**Comment by andreamazz** [comment]
That's just due to how the sample is set up, if you extend the view controller's main view to be under the bottom safe are, the footer goes under.

**Comment by andreamazz** [comment]
Fixed in master. Feedback is welcome.
