### ISSUE TITLE
IOS 9 -> navigationbar overlay tableview

### ISSUE THREAD

**Issue by fukemy** [andreamazz/AMScrollingNavbar#320]
Hello. Thanks you for great library, tested ok in IOS 11.
 But in IOS9 the navigation bar overlay tableview, i tried to set tableview content insets but it's not working.

 In layout interfacebuilder, i set top contraint of tableview to super view = 0, not safe area. 
Here is my picture
![screen shot 2018-07-16 at 16 14 12](https://user-images.githubusercontent.com/8202437/42751092-caf03a2e-8913-11e8-9959-509123fc73f2.png)

**Comment by andreamazz** [comment]
Hi @fukemy 
sorry to hear that, but I see no point in supporting iOS9 at the moment. If you find the specific issue in the code I'll be happy to push a fix, but I'm not going to debug an obsolete version of iOS.

**Comment by fukemy** [comment]
Hi. Thanks you for quick response. 
May be other will need it: 
```
if responds(to: #selector(getter: edgesForExtendedLayout)){
                edgesForExtendedLayout = UIRectEdge(rawValue: 0);
            }
```
