### ISSUE TITLE
The TabBar does not appear when resuming from a video inside a WKWebView

### ISSUE THREAD

**Issue by L4grange** [andreamazz/AMScrollingNavbar#321]
**Describe the bug**
Hello. First of all I want to thank you for this library, it has helped me very much!
The bug I'm facing is that I have a WKWebView that makes my NavBar and TabBar hide when scrolled. When the navigaiton elements are hidden and a youtube video begins playing inside the webView, when I dismiss the video from fullscreen, the TabBar does not appear again, but stays hidden untill I kill the app and restart it. The navigation bar appears, but its title is Hidden, untill I scroll again, and the title appears as normal.

**To Reproduce**
1. Create a WKWebView
2. Make the NavBar and the TabBar follow the webView
4. Play any video that will show the fullscreen ios video player.
5. Exit the fullscreen video
6. The NavBar has appeared (but its title is hidden), but the TabBar is still hidden and does not re-appear when scrolling.

**Expected behavior**
The TabBar should also re-appear when entering a fullscreen video in a webView, along with the NavBar

Thank you for your time!

**Comment by andreamazz** [comment]
Hey @L4grange 
I'm a little swamped at the moment, so I've tried a quick blind fix in c708417.
Can you test it out?

**Comment by L4grange** [comment]
Thank you for your fast response! Will test ASAP and report here.

**Comment by andreamazz** [comment]
Great to hear. I'll push a new release with the fix.
