### ISSUE TITLE
Add some Settings

### ISSUE THREAD

**Issue by hms040717007** [andreamazz/AMScrollingNavbar#324]
1.add Settings that hide the top status bar
2.add gesture slide-on or off Settings
3.add gradient navigation bar Settings
4.add Settings for custom controls on the navigation bar and callbacks to click events
5.add basic Settings on the navigation bar (such as font color, font size, underline, and background color set), which I suggest can be set to use as a singleton
6.It is recommended that you change the delegate method to an attribute
![1534995934305](https://user-images.githubusercontent.com/17900926/44503729-7321ce00-a6ca-11e8-8770-b8520f8e1c09.jpg)

**Comment by andreamazz** [comment]
This all can be done on UINavigationBar and UINavigationController, so I fail to see the point of this.
