### ISSUE TITLE
[strong bug] Error in isUserInteractionEnabled (Please treat preferentially) 

### ISSUE THREAD

**Issue by StefaniOSApps** [andreamazz/AMScrollingNavbar#332]
**Describe the bug**
Although i have reported many bugs for some days, i really like this framework 👍 !! 

Well, I noticed that the UIBarButtonItem sometimes did not work in the UiNavigationBar (because, userInteractionEnabled = false). I did not understand why and it really annoyed me. Now I have found the reason why it is.

**To Reproduce**
1. Look down at my small example. >> RUN
2. First, hide the NavBar by scrolling down
2. If you just scroll up so far that the NavBar is halfway visible, then you lift the finger off. The scrollbar now expands by itself. The status of userInteractionEnabled is now false. So you can not tap the button on UiNavigationBar. 

The bug was created at:

` navigationBar.isUserInteractionEnabled = (newState == .expanded)`

on line 448 at ScrollingNavigationController.swift

**Expected behavior**
The UIBarButtonItems should always have (userInteractionEnabled = true) after finished scrolling

**Example GIT**
https://github.com/StefaniOSApps/Example

**Comment by DaveMcKraken** [comment]
I was just working on this bug yesterday and trying to figure it out. Thanks to @StefaniOSApps  pinpointing the cause, I found a workaround with the delegate that will help until Andreamazz can fix it:

```
func scrollingNavigationController(_ controller: ScrollingNavigationController, willChangeState state: NavigationBarState) {
    if controller.percentage < 0.5 {
      controller.navigationBar.isUserInteractionEnabled = true
    }
  }
```

**Comment by StefaniOSApps** [comment]
It is possible with:

```
#pragma ScrollingNavigationControllerDelegate
- (void)scrollingNavigationController:(ScrollingNavigationController *)controller willChangeState:(enum NavigationBarState)state{
    if ([controller percentage] < 0.5) {
        [[controller navigationBar] setUserInteractionEnabled:true];
    }
}
```

to fix the bug until to the next update. Unfortunately, the "willChangeState" function must be used because "didChangeState" is not used in the framework code.

In order to get the delay of the function "didChangeState", 

```
#pragma ScrollingNavigationControllerDelegate
- (void)scrollingNavigationController:(ScrollingNavigationController *)controller willChangeState:(enum NavigationBarState)state{
    if ([controller percentage] < 0.5) {
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, 0.5 * NSEC_PER_SEC), dispatch_get_main_queue(), ^{
            [[controller navigationBar] setUserInteractionEnabled:true];
        });
    }
}
```
can also be used.

**do not forget:**
`[(ScrollingNavigationController *)self.navigationController setScrollingNavbarDelegate:self];`

**many thanks to @Dave**

**Comment by StefaniOSApps** [comment]
The best would be if the function
`controller.navigationBar.isUserInteractionEnabled = true`
 is inserted in a completion block of UIView.animate.

OR

use: scrollingNavigationController(controller:**did**ChangeState state:),

after the implementation of it (see bug #333)

**Comment by StefaniOSApps** [comment]
What's the reason that controller.navigationBar.isUserInteractionEnabled is set to false? Is this even necessary? @DaveMcKraken
