### ISSUE TITLE
scrollingNavigationController:didChangeState never calling

### ISSUE THREAD

**Issue by StefaniOSApps** [andreamazz/AMScrollingNavbar#333]
**Describe the bug**
The func scrollingNavigationController:didChangeState is never calling. (ScrollingNavigationControllerDelegate)

**To Reproduce**
1. Open Demo
2. Search for "didChangeState"
3. Only one result at line 12 on ScrollingNavigationController.swift:
`@objc optional func scrollingNavigationController(_ controller: ScrollingNavigationController, didChangeState state: NavigationBarState)` **(never used)**

**Expected behavior**
Presumably it was forgotten to use this function in the code. Please insert this function in the "completion" block of "UiView.animate".

**Comment by andreamazz** [comment]
Fixed in #341
