### ISSUE TITLE
followScrollView not in bridging header for objective C

### ISSUE THREAD

**Issue by StainlessStlRat** [andreamazz/AMScrollingNavbar#334]
**Describe the bug**
I am using the POD installation with the POD command: pod 'AMScrollingNavbar'
It installed AMScrollingNavbar (5.1.0)

The function: 
is not located in the swift bridging header (but other ones like stopFollowing are)

**To Reproduce**
1. Import at top 
<AMScrollingNavBar/AMScrollingNavBar-Swift.h>
2. Try to implement followScrollView
ScrollingNavigationController *navController = (ScrollingNavigationController*)self.navigationController;
    [navController followScrollView:_tableView delay:0 scrollSpeedFactor:1 collapseDirection:NavigationBarCollapseDirectionScrollDown followers:nil];
3. Observe error:
No visible @interface for 'ScrollingNavigationController' declares the selector 'followScrollView:delay:scrollSpeedFactor:collapseDirection:followers:'

I also had set my root nav controller to be a ScrollingNavigationController one and got this:
Unknown class ScrollingNavigationController in Interface Builder file.

**Expected behavior**
Compiles and runs fine in interface builder as well as code

**Comment by andreamazz** [comment]
https://github.com/andreamazz/AMScrollingNavbar/issues/327

Use `5.1.1`

**Comment by StainlessStlRat** [comment]
Thank you for the blazing fast response!

**Comment by StainlessStlRat** [comment]
Note: I still get:

Unknown class ScrollingNavigationController in Interface Builder file.

Resulting in the nav controller defaulting to a default one
