### ISSUE TITLE
Can not move rows in UITableView

### ISSUE THREAD

**Issue by StefaniOSApps** [andreamazz/AMScrollingNavbar#340]
**Describe the bug**
You can not move rows in UITableview

**Demo Project**
https://github.com/StefaniOSApps/Example
Run Demo

**Expected behavior**
Can move rows to each position.

**Comment by StefaniOSApps** [comment]
How can we check if a UITableViewCell is moving in scrolling view ?

I think the solution we can found in 

```
open func gestureRecognizerShouldBegin(_ gestureRecognizer: UIGestureRecognizer) -> Bool {
        guard let gestureRecognizer = gestureRecognizer as? UIPanGestureRecognizer else { return true }
        let velocity = gestureRecognizer.velocity(in: gestureRecognizer.view)
        return abs(velocity.y) > abs(velocity.x)
    }
```

how can we can proof if a UITableViewCell is moving ?

**Comment by andreamazz** [comment]
Checkout latest commit

**Comment by StefaniOSApps** [comment]
**Reopen it**

```
 if let tableView = scrollableView as? UITableView, tableView.isEditing {
            return
        }
```

it is not the best solution, because the UITableView with tableView.isEditing = true, does not allow to hide the NavBar (always). 

I hope you know that tableView.isEditing is not the same one as moving UITableViewCell
It must be asked directly if a cell is being moved at this moment

**Comment by StefaniOSApps** [comment]
i have been updated the demo project with the current solution

https://github.com/StefaniOSApps/Example
check it out

**Comment by andreamazz** [comment]
I could, but the starting issue remains, I'm not aware of a public API that tells you whether a cell is being dragged or not. I'll do some digging and let you know.

**Comment by andreamazz** [comment]
Maybe checking if a single cell is both in editing and highlighted? 🤔

**Comment by StefaniOSApps** [comment]
I had already tested everything. I also checked the alpha value of the subviews, but without success.

I have solved this problem:

**ADD**
```
/**
     Defaults to `true`
     */
    open var showAlwaysNavigationBarWhileEditing = true
```

**CHANGED**
```
if let tableView = scrollableView as? UITableView, tableView.isEditing, showAlwaysNavigationBarWhileEditing {
            return
}
```

**SET**
```
[(ScrollingNavigationController *)self.navigationController setShowAlwaysNavigationBarWhileEditingmode:true];
```

i have been updated the demo project with the current solution

https://github.com/StefaniOSApps/Example
check it out

**Comment by andreamazz** [comment]
That's fine, but if the library user doesn't set that flag, the editing behavior will be broken like in your starting project. I rather have a more robust solution, I'll let you know if I can find it, if I can't I'll add that flag.

**Comment by StefaniOSApps** [comment]
No, I do not think so. The function `gestureRecognizer?.cancelsTouchesInView = false` already enough, so that everything works.

The user can set in his own Project 
`[ScrollingNavigationController setShowAlwaysNavigationBarWhileEditing:true];` (default is true).

I think this solution is the best and my fork (branch master) use this way.

**Comment by andreamazz** [comment]
Ok, sounds reasonable. Added `shouldScrollWhenTableviewIsEditing` in the latest commit.

**Comment by StefaniOSApps** [comment]
thanks
