### ISSUE TITLE
Need prefersStatusBarHidden in ScrollingNavigationController

### ISSUE THREAD

**Issue by StefaniOSApps** [andreamazz/AMScrollingNavbar#344]
**Describe the bug**
I want to hide the `UIStatusBar` at some `UIViewControllers`. The Problem is I use the popular `RESideMenu` framework with more than 7k stars (https://github.com/romaonthego/RESideMenu). 

The structure is:

1. `ScrollingNavigationController`
2. present a `RESideMenu` controller with
2.a `UIViewController` (left)
2.b `UIViewController` (right)
2.c `UIViewController` (content - center)

The `RESideMenu` ask the `ScrollingNavigationController` which state the `prefersStatusBarHidden` has. So I need this feature. `[[UIApplication sharedApplication] setStatusBarHidden:YES]; ` is deprecated since iOS 7. Only `prefersStatusBarHidden` works.

I will create a PR with this feature. So can set this state by `shouldPrefersStatusBarHidden`. 
Default is `false`.

**Comment by andreamazz** [comment]
Subclass the `ScrollingNavigationController` and override that property. There is no need to add another property.

**Comment by StefaniOSApps** [comment]
did you remember ?
https://github.com/andreamazz/AMScrollingNavbar/issues/327#issuecomment-428852427

**Comment by StefaniOSApps** [comment]
... My complete project is in Objective C, so I'd like to favor this feature. Otherwise I would have to write my own subclass for this single feature. Do not you think that this is unnecessary? It would make me really happy :-)  This also applies to others.

**Comment by andreamazz** [comment]
> ... My complete project is in Objective C,

You are using this library, so it's not really just ObjC. At any rate, the two languages are interoperable, so I fail to see the issue.

> Otherwise I would have to write my own subclass for this single feature. 

Like you would if you'd use a plain UINavigationController. Should I add a property for every possible override? It would pollute the API, that I intend to keep as close to the default implementation of the nav controller as possible.

**Comment by StefaniOSApps** [comment]
Right, I use Swift Frameworks. But not in my main project with more than 50 UIViewControllers. The reason is simple. Swift was very often modified by Apple Inc. Objective C is more consistent.

I do not think that will pollute the framework. Also the successful framework RESideMenu with more than 7000 likes uses this feature (https://github.com/romaonthego/RESideMenu). This is also a specific UINavigationController extension.

<img width="1088" alt="bildschirmfoto 2018-10-19 um 22 50 49" src="https://user-images.githubusercontent.com/29314643/47243191-937fb780-d3f1-11e8-90c6-bcb9d9f74d5a.png">

**Comment by andreamazz** [comment]
He does that because there's some extra logic behind it: it's hidden (or not) when the menu is visible, and that's a piece of information that shouldn't be handled by the library user. It make sense in Roman's library, not in this one. The decision is final.
