### ISSUE TITLE
Use of unresolved identifier 'showNavBarAnimated'  swift 4.2,

### ISSUE THREAD

**Issue by Iammahiiii** [andreamazz/AMScrollingNavbar#360]
**Describe the bug**
I am trying to upgrade an old project from Swift 1.2 to Swift 4.0, I see the following error "Use of unresolved identifier 'showNavBarAnimated' "
**To Reproduce**
Upgrade an old project from Swift 1.2 to Swift 4.01. Do this
**Expected behavior**

**Screenshots**

**Comment by andreamazz** [comment]
Second line of the readme:
> Version 2.x is written as a subclass of UINavigationController, in Swift.

The implementation changed completely, check out the docs to get started.

**Comment by andreamazz** [comment]
The API obviously changed, follow the readme.
