### ISSUE TITLE
Scroll to top doesn't work correctly in case of navigationBar without searchController

### ISSUE THREAD

**Issue by arashetm** [andreamazz/AMScrollingNavbar#363]
**Describe the bug**
When 'searchController' is off tapping on the collapsed navigationBar doesn't scroll to top correctly. 

**To Reproduce**
1. try to comment `navigationItem.searchController = UISearchController(searchResultsController: nil)` in 'TableViewController'
2. Observe error

**Expected behavior**
Scroll to top correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/19370820/59337567-1c978600-8d16-11e9-9793-a193607a5023.png)

**Comment by arashetm** [comment]
@andreamazz could you help me please

**Comment by andreamazz** [comment]
Hey @arashetm 
it's an issue that came up wth iOS12 IIRC, for the moment I can only offer a dirty fix:
```swift
  open func scrollViewShouldScrollToTop(_ scrollView: UIScrollView) -> Bool {
    if let navigationController = self.navigationController as? ScrollingNavigationController {
      navigationController.showNavbar(animated: true)
      navigationController.scrollView()?.setContentOffset(CGPoint(x: 0, y: -200), animated: true)
    }
    return false
  }
```
I'e put an hardcoded `-200` there since I cant find the proper amount (the full navbar height i snot enough for some reason).

**Comment by arashetm** [comment]
@andreamazz I've tried this but does not work, the problem still remains.

**Comment by Alexookah** [comment]
@andreamazz this should be closed as well
