### ISSUE TITLE
Live demo at https://appetize.io fails to get launched

### ISSUE THREAD

**Issue by valeriyvan** [andreamazz/AMScrollingNavbar#370]
**Describe the bug**
Live demo at https://appetize.io fails to get launched.

**To Reproduce**
1. Follow link Live demo from https://github.com/andreamazz/AMScrollingNavbar
2. Tap [Tap to play]
3. Observe crash of demo app

**Expected behaviour**
Demo app is expected to run.

**Screenshots**
n/a

**Comment by andreamazz** [comment]
Should be ok now
