### ISSUE TITLE
Scroll to Top is not exact correct

### ISSUE THREAD

**Issue by Alexookah** [andreamazz/AMScrollingNavbar#377]
I tried to tap on the status bar to initiate scroll to top and it seems that the navbar is showing but the scrollview is not going exactly to the top.

check the following video:
https://streamable.com/5osha

this line is responsible for the scrolling to top:
https://github.com/andreamazz/AMScrollingNavbar/blob/master/Source/ScrollingNavigationController.swift#L263

maybe this has to happen after the navbar has been shown?

similar issue:
https://github.com/andreamazz/AMScrollingNavbar/issues/363

**Comment by andreamazz** [comment]
Hey @Alexookah 
check out master for a fix. I've added `scrollToTop` to the `showNavbar` call, optional, default set to false

**Comment by Alexookah** [comment]
@andreamazz 
It works perfect when there are no followers.
With follower it needs the height of followers.
How to calculate that?

**Comment by Alexookah** [comment]
@andreamazz 
You forgot to handle the scrollToTop inside the function ?

i tried this for one follower which seems ok
let size = CGPoint(x: 0, y: -(self.followers.first?.view?.frame.height ?? 0))

maybe create a computer variable that returns for all followers the height?

**Comment by andreamazz** [comment]
Right, added to master and fixed the missing check

**Comment by andreamazz** [comment]
Pushed a minor update that filters the followers:
let followersHeight = self.followers.filter { $0.direction == .scrollUp }.compactMap { $0.view?.frame.height }.reduce(0, +)

**Comment by Alexookah** [comment]
nice @andreamazz 
great job
closing the issue

**Comment by Alexookah** [comment]
@andreamazz 
Sorry for all the fuzz.
After checking with my configuration i had to add an additionalScrollToTopOffset
made a pull request for this.

https://github.com/andreamazz/AMScrollingNavbar/pull/378
hope its not too late.

**Comment by Alexookah** [comment]
PL merged
Thanks so much @andreamazz

**Comment by arashetm** [comment]
> @andreamazz
> Sorry for all the fuzz.
> After checking with my configuration i had to add an additionalScrollToTopOffset
> made a pull request for this.
> 
> #378
> hope its not too late.

The `additionalScrollToTopOffset` is always zero!
you didn't set it anywhere!
