### ISSUE TITLE
Can't not submit app to AppConnect since UIWebView is deprecated.

### ISSUE THREAD

**Issue by ttmdung203** [andreamazz/AMScrollingNavbar#395]
**Describe the bug**
I got message from Apple when uploading application to AppConnect

> ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

**Screenshots**
![Screen Shot 2020-07-22 at 2 00 22 PM](https://user-images.githubusercontent.com/12870242/88145241-55e23b00-cc24-11ea-979a-8ddc07cba4b4.png)

**Comment by andreamazz** [comment]
Are you using an older version?
See changelog: https://github.com/andreamazz/AMScrollingNavbar/blob/daa39982f4dfa5751874ae0da0fc121c651f878e/CHANGELOG.md#540

**Comment by ttmdung203** [comment]
Ooops! You're right, Sorry for the question. Many thanks for your fast response. It works for me now. Thanks so much.
