### ISSUE TITLE
Weird behaviour after accessing bottomLayoutGuide with iOS14

### ISSUE THREAD

**Issue by wmadao11** [andreamazz/AMScrollingNavbar#397]
@**Describe the bug**

Once I access ScrollingNavigationController's `bottomLayoutGuide.length`  (even just print it), the awsome scrolling behaviour will be broken. I know `bottomLayoutGuide` was deprecated, but another library I used called this property. 

- This only happened with iOS14, Xcode12.0.
- If I changed to use `safeAreaInsets.bottom`, this fixed.

**To Reproduce**
1. Clone the source code, open demo project.
2. In any child view controller , call `navigationController?.bottomLayoutGuide.length`

**Expected behavior**
Scrolling behaviour goes well as usual.

**Screenshots**
[Here are the reproduction codes](https://github.com/wmadao11/AMScrollingNavbar/blob/bfbedd0a92/Demo/ScrollingNavbarDemo/ViewControllers/CollectionViewController.swift#L27)

![Sep-24-2020 15-01-09](https://user-images.githubusercontent.com/16165094/94111815-24c9f500-fe77-11ea-9897-c569045db6be.gif)

**Comment by andreamazz** [comment]
Hey @wmadao11 
yikes! UIKit is fighting back.
I'm not sure how to fix this to be honest, probably one way would be to override `bottomLayoutGuide` in the controller, but it's not something that I'd put in the codebase for everyone. 
What's the other library?

**Comment by wmadao11** [comment]
@andreamazz 
Thanks for your quick reply. Yes it seems not directly correspond as a bug on your end but a UIKit error. However, since I am actually an iOS beginner so I can't find out more info about this  :(

> What's the other library? 

It's [PanModal](https://github.com/slackhq/PanModal). As I said, if I changed to use `safeAreaInsets.bottom`, this fixed. So I [committed a PR](https://github.com/slackhq/PanModal/pull/117) for them to fix my project temporarily.

**Comment by andreamazz** [comment]
Great 👍 
Closing this for the time being, feel free to reopen if needed.
