### ISSUE TITLE
Navbar is not hiding in iOS 14

### ISSUE THREAD

**Issue by jenixgnanadhas** [andreamazz/AMScrollingNavbar#403]
**Describe the bug**
Im currently using version v5.6.0. The nav bar disappears perfectly after calling 

```
navigationController.showNavbar()
navigationController.followScrollView(tableView, delay: 0.0) 
```
in my **viewWillAppear**. I upgraded my project to Xcode 12.5 and it stopped working in iOS 14 (The Navbar is still visible)
It works fine in iOS 13 and below.

Any Idea what might've gone wrong ?. I tried updating to 5.7.3 and still i see the issue.
Thanks in Advance :)

**Comment by andreamazz** [comment]
Hi @jenixgnanadhas 
The sample project seems to run fine, can you reproduce the issue there?
