### ISSUE TITLE
Fatal Exception: NSInternalInconsistencyException UICollectionView received layout attributes for a cell with an index path that does not exist: <NSIndexPath: 0xcf6b25b9e4f777ac> {length = 2, path = 0 - 2}

### ISSUE THREAD

**Issue by avneeshagr** [andreamazz/AMScrollingNavbar#405]
**Describe the bug**
A crash is happening Intermittently. (for version 5.7.3)
Error message :
Fatal Exception: NSInternalInconsistencyException UICollectionView received layout attributes for a cell with an index path that does not exist: <NSIndexPath: 0xcf6b25b9e4f777ac> {length = 2, path = 0 - 2}

**Expected behavior**
No Crash should be there.

**Screenshots**
Attaching a screenshot of the stack trace for reference from firebase.

<img width="1243" alt="Screenshot 2021-10-14 at 12 49 25 PM" src="https://user-images.githubusercontent.com/67959794/137270427-50506937-4728-45e2-a7e4-5c43f80f61d1.png">

**Comment by andreamazz** [comment]
I don't see how it's related to this library, the crash occurs on a UICollectionView after a layout change.
