### ISSUE TITLE
After scroll, the scrollview inset is wrong

### ISSUE THREAD

**Issue by yichen** [andreamazz/AMScrollingNavbar#50]
Hi, I am using this in a UIViewController, as a child view controller of a uitabbarcontroller. After scroll, the tableView (root view in UITableviewController) will have an offset below the navigation bar. The extra space is about the height of the navigation bar. From Xcode, if I uncheck the `Adjust Scroll View Insets` checkbox for the view controller, the extra space will disappear after scroll, but the content section will go under the nav bar before the scroll.

To repro this, go with the instruction video, but after embedding the UIViewController with a navigation controller, connect this navigation controller to a UITabbarController. I am using the latest version 1.0, installed via cocoapod.

**Comment by khaskheli24** [comment]
Hi i am using AMScrolling with uitableview with uiviewcontroller that loaded to uicontainer view. 
where AMScrolling does  not working, any hint

**Comment by khaskheli24** [comment]
is any way AMScrollingnavBar may work in ContainerView please help
