### ISSUE TITLE
ScrollableView frame problem after scrolling

### ISSUE THREAD

**Issue by tfonfara** [andreamazz/AMScrollingNavbar#57]
Hi,

I found a problem in line 353 of your category:
```frame.size.height = [UIScreen mainScreen].bounds.size.height - frame.origin.y;```
In my case, the scrollable view is the content of a tab bar view controller. With the line above the scrollable view will be resized by ignoring the tab bar.

As improvement, I would appreciate if you could change this part like this (line numbers refers to commit eef1dbd57a80e81fc9b96f5527efe5705062ec2a)

1. Line 40: New property for initial height of the scrollable view
```
- (void)setInitialScrollableViewHeight:(float)initialScrollableViewHeight { objc_setAssociatedObject(self, @selector(initialScrollableViewHeight), [NSNumber numberWithFloat:initialScrollableViewHeight], OBJC_ASSOCIATION_RETAIN); }
```
 ```
- (float)initialScrollableViewHeight { return [objc_getAssociatedObject(self, @selector(initialScrollableViewHeight)) floatValue]; }
```

2. Line 50: Reset the height if ```followScrollView:``` is called
```
[self setInitialScrollableViewHeight:0.0f];
```

3. Line 202: Save the height of the scrollable view's superview on first scrolling
```
if ([self initialScrollableViewHeight] == 0.0f) {
        [self setInitialScrollableViewHeight:self.scrollableView.superview.bounds.size.height];
}
```

4. Line 353: Use initialScrollableViewHeight instead of [UIScreen mainScreen]
```
    if (frameNav.origin.y == [self statusBar]) {
        frame.size.height = [self initialScrollableViewHeight];
    } else {
        frame.size.height = [self initialScrollableViewHeight] + frameNav.size.height;
    }
```

Thank you!

**Comment by andreamazz** [comment]
Closing this issue. Please refer to this https://github.com/andreamazz/AMScrollingNavbar/issues/146
