### ISSUE TITLE
uinavigationbar title scrolls over status bar in uipageviewcontroller

### ISSUE THREAD

**Issue by tomonariokubo** [andreamazz/AMScrollingNavbar#70]
Hello, thanks for the useful library.
I want to use it in uipageviewcontroller and made sample app.
I've encountered a problem as screenshots.
The title 'Scroll Navigation Bar' scrolls over status bar.
Please let me know if you have any solution.

![screen shot 2014-08-24 at 2 52 46 pm](https://cloud.githubusercontent.com/assets/3293712/4022700/f566d8e4-2b52-11e4-8ebe-2e6ac7f88471.png)
![screen shot 2014-08-24 at 2 53 02 pm](https://cloud.githubusercontent.com/assets/3293712/4022701/faec8732-2b52-11e4-8da3-4ed18b7ffcb4.png)

RootViewController.m
- (void)viewDidLoad
  {
  ...
  [self setTitle:@"Scroll Navigation Bar"];
  self.navigationController.navigationBar.barTintColor = [UIColor yellowColor];
  [self.navigationController.navigationBar setTranslucent:YES];
  ...
  }

DataViewController.m
- (void)viewDidLoad
  {
  ...
  [self followScrollView:self.tableView];
  ...
  }

**Comment by Alexookah** [comment]
@andreamazz any thoughts of making this work with UIPageViewController?
