### ISSUE TITLE
navigationItem.titleView not show

### ISSUE THREAD

**Issue by ethanvictory** [andreamazz/AMScrollingNavbar#75]
1.download / run demo project
2.tap Table View demo
3.tap select any row into another table view
4.scroll down then navigation hide
5.press power button, make phone sleep
6.press home button, awake phone, and will see navigation bar is show but item not show

**Comment by andreamazz** [comment]
Closing this issue. Please refer to this https://github.com/andreamazz/AMScrollingNavbar/issues/146
