### ISSUE TITLE
Pushing UIView Elements Down

### ISSUE THREAD

**Issue by Explicit-CB** [andreamazz/AMScrollingNavbar#77]
Ever since I added this library (which works perfectly by the way) my elements contained in normal UIView's seem to be pushed down by roughly the same height as the navigation controller.

I am running iOS 8 GM and using Swift.

**Comment by eremzeit** [comment]
I have (I think) the same problem.  Are you sure it's the children views getting pushed down and not the UIViewController's frame being set too high?

In my case, the UIViewController (the one that called `followScrollView`) is in the correct position at first but then once I scroll enough to start the scrolling navbar, the UIViewController is rendered what I measure to be a navigation bar's height below whereever the bottom of the navigation bar is.  As an example, the frame of the UIViewController when the navigation bar is scrolled into a collapsed state is `{{0, 31}, {375, 636}}`, where the height of 31 appears to be the height of collapsed nav bar.

Setting the nav bar to be translucent doesn't fix the issue.

![image](https://cloud.githubusercontent.com/assets/1264533/6743102/180034ec-ce53-11e4-8f54-d426b2266cb3.png)

**Comment by andreamazz** [comment]
Closing this issue. Please refer to this https://github.com/andreamazz/AMScrollingNavbar/issues/146
