### ISSUE TITLE
As shown in figure

### ISSUE THREAD

**Issue by DongjieLi** [andreamazz/AMScrollingNavbar#80]
![screen shot 2014-10-08 at 7 55 24 pm](https://cloud.githubusercontent.com/assets/7219185/4558602/01ab9a88-4ee2-11e4-9399-ad33b5ce381a.png)
![screen shot 2014-10-08 at 7 55 36 pm](https://cloud.githubusercontent.com/assets/7219185/4558601/01a60c62-4ee2-11e4-8454-a2faa493a126.png)

**Comment by andreamazz** [comment]
Closing this issue. Please refer to this https://github.com/andreamazz/AMScrollingNavbar/issues/146
