### ISSUE TITLE
Deleting Elements Issue

### ISSUE THREAD

**Issue by dehli** [andreamazz/AMScrollingNavbar#84]
Hello, thanks for an amazing library! I discovered a bug. These are the steps to reproduce it.

1. Start with a tableview with 3 cells.
2. Scroll down so the nav bar disappears.
3. Delete 2 of the cells.
4. Scroll up to get the nav bar back. 

Step 4 doesn't work. Since the nav bar doesn't disappear when there are a few cells, it won't reappear. Not sure if you've noticed this before.

**Comment by andreamazz** [comment]
Closing this issue. Please refer to this https://github.com/andreamazz/AMScrollingNavbar/issues/146
