### ISSUE TITLE
If you scroll up slowly in tableview Nav bar does not appear

### ISSUE THREAD

**Issue by spennyf** [andreamazz/AMScrollingNavbar#86]
As can be seen in pics below you can be at the top of the screen and have no nav bar, how could it be changed or fixed so that if you are at the top the nav bar is always there.
![ios simulator screen shot nov 14 2014 1 41 18 pm](https://cloud.githubusercontent.com/assets/7727994/5051270/0caac1cc-6c04-11e4-99fd-f79813647884.png)
This is at top normal

![ios simulator screen shot nov 14 2014 1 41 26 pm](https://cloud.githubusercontent.com/assets/7727994/5051274/154f1116-6c04-11e4-8577-86340216d3e9.png)

This is at top when slowly scrolled back up

**Comment by andreamazz** [comment]
Closing this issue. Please refer to this https://github.com/andreamazz/AMScrollingNavbar/issues/146
