### ISSUE TITLE
Tapping searchBar does nothing

### ISSUE THREAD

**Issue by SimonasA** [andreamazz/AMScrollingNavbar#87]
Steps to reproduce:
1. Launch demo app
2. Choose "Table View"
3. Scroll down
4. Tap on search bar

Expected behaviour: Search controller would expand
Actual behaviour:  Nothing happens

Ability to reproduce: 100%

Screenshot:
![ios simulator screen shot 2014 lapkr 20 17 41 03](https://cloud.githubusercontent.com/assets/3868554/5127444/f0121c94-70dc-11e4-933e-f772112c2332.png)

**Comment by andreamazz** [comment]
Sadly, no, updating the constraint instead of the frame does not extend the superview's frame.

**Comment by Igor-Palaguta** [comment]
As a solution override pointInside of controller's view

e.g. in Swift
```
class ScrollingView: UIView {
   @IBOutlet private weak var topConstraint: NSLayoutConstraint!

   override func pointInside(point: CGPoint, withEvent event: UIEvent?) -> Bool {
      var viewRect = self.bounds
      viewRect.origin.y = self.topConstraint.constant
      viewRect.size.height += -self.topConstraint.constant
      return viewRect.contains(point)
   }
}
```

**Comment by andreamazz** [comment]
Closing this issue. Please refer to this https://github.com/andreamazz/AMScrollingNavbar/issues/146
